### ISSUE TITLE
nitpicking: symmetric hint positions

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#101]
This is a very minor issue which would probably only be noticed by perfectionists: Currently the hint positions are calculated in an asymmetrical way. How about first trimming the screen edges until both width and height are divisible by the number of hint keys and then calculating the positions (so that left/right and top/bottom gaps at the edges have identical sizes, respectively)?

**Comment by rvaiya** [comment]
Fixed in the latest commit.

**Comment by herrsimon** [comment]
Thanks! For my resolution it is still somewhat asymmetric so I took a shot at it myself. Sorry for the copy&paste and not creating a proper pull request, I never did this here on github and setting it up directly from the command line seems to be somewhat involved. Please let me know if you would like me to do it anyway.

The asymmetry should now be as small as possible and `hint_size` now corresponds to the percentage of vertical/horizontal space used by the hints (so that its square gives the percentage of covered screen area). At the cost of including math.h, one could directly make `hint_size` correspond to the occupied screen area.

In `hint.c`, the corresponding function is 
```
size_t generate_hints(screen_t scr, struct hint *hints)
{
	int sw, sh;
	int i, j;
	size_t n = 0;

	const char *chars = cfg->hint_chars;
	const int nr = strlen(chars);
	const int nc = strlen(chars);

	screen_get_dimensions(scr, &sw, &sh);

        /* hint_size corresponds to the percentage of column/row space
         * taken up by the hints. At the cost of including math.h, one
         * could replace cfg->hint-size / 100 by its square root, so
         * that hint_size corresponds to the approximate percentage of
         * screen area taken up by the hints
         */

        const int w = sw / nc * cfg->hint_size / 100;
        const int h = sh / nr * cfg->hint_size / 100;

        const int colgap = sw / nc - w;
        const int rowgap = sh / nr - h;

        const int x_offset = (sw - nc * w - (nc - 1) * colgap) / 2;
        const int y_offset = (sh - nr * h - (nr - 1) * rowgap) / 2;

        int x = x_offset;
        int y = y_offset;

        for (i = 0; i < nc; i++) {
		for (j = 0; j < nr; j++) {
			struct hint *hint = &hints[n++];

			hint->x = x;
			hint->y = y;

			hint->w = w;
			hint->h = h;

			hint->label[0] = chars[i];
			hint->label[1] = chars[j];
			hint->label[2] = 0;

			y += rowgap + h;
		}

		y = y_offset;
		x += colgap + w;
	}

	return n;
}
```

Proposal for the man page:

```
*hint_size*: Hint size. Must be a number between 1 and 100 and corresponds to the approximate percentage of horizontal/vertical space occupied by the drawn hints. The default value covers approximately 71% of horizental/vertical space, which corresponds to 50% (the square of 71%) of total screen area. (default: 71).
```

And finally the default for `hint_size` should be set accordingly.

**Comment by herrsimon** [comment]
managed to install the hub tool and created my first pull request on github. Yay!

**Comment by rvaiya** [comment]
Thanks! For my resolution it is still somewhat asymmetric so I took a shot at it myself. Sorry for the copy&paste and not creating a proper pull request, 

> I never did this here on github and setting it up directly from the command line seems to be somewhat involved.

No worries, the PR looks fine :).

> The asymmetry should now be as small as possible and hint_size now corresponds


I have no objection to your patch, but I'm not sure I understand what you mean by 'asymmetry'.  The size of the left and right margins should be identical (colgap).

You patch minimizes the distance to the screen edge (which is nicer), but I don't believe it adds any additional symmetry.

**Comment by herrsimon** [comment]
Happy to hear that you like the patch!

> I have no objection to your patch, but I'm not sure I understand what you mean by 'asymmetry'. The size of the left and right margins should be identical (colgap).

Well, if screen width is not divisible by the number of hint characters, the truncated pixels currently all end up on the right (after the last hint in the row), or am I wrong here? A similar argument applies to the height. The updated algorithm spreads these pixels evenly to the left/right and top/bottom, with an unnoticeable one pixel difference when the excess is odd.

**Comment by rvaiya** [comment]
>  or am I wrong here?

Oops. You are indeed correct, my apologies. I hadn't noticed the issue since it wasn't a problem at my resolution.
