### ISSUE TITLE
the function request and a bug

### ISSUE THREAD

**Issue by alongnice** [rvaiya/warpd#102]
The function request

First of all, this project is really cool.

My problem is that I have two screens and my operating system is UOS. I set the shortcut keys to open WARpd, but each time it only runs on one of my screens, the one where the mouse was originally,(I'm not sure) I would like developers to consider this application scenario if possible.

By the way, I have installed kali Linux system on my laptop. In the prompt mode, there is no response when I press the position I want to click. 

There are two questions in total, and I can ask them separately if necessary.

**Comment by rvaiya** [comment]
There is a dedicated screen mode (`s`). Please see the man page for two details.
