### ISSUE TITLE
Not Checking if .config Dir Exists

### ISSUE THREAD

**Issue by p0da** [rvaiya/warpd#106]
Seems like warpd is not checking if the .config directory exists which leads to "flock open: No such file or directory" on running warpd without a ${HOME}/.config (relevant code seems to be  [here](https://github.com/rvaiya/warpd/blob/133b8a2bd99359baa826c424f90afe3d93434527/src/warpd.c#L222)). You may want to also consider implementing the XDG spec in warpd which would allow specifying the location of an alternative .config dir.

**Comment by rvaiya** [comment]
Thanks. I believe this should be fixed.

**Comment by rvaiya** [comment]
You are indeed correct, that was my original intention. I have fixed this in the latest commit, thanks for catching this.

**Comment by rvaiya** [comment]
Oops. Third time is the charm :P.

> the lockfile should be put in XDG_RUNTIME_DIR ("standard" name could be
> warpd.lock) or, if it doesn't exist, in a directory with "similar capabilities"
> (/tmp/warpd/lock would be a good candidate) upon issuing a warning.

I prefer storing state in one location. XDG_RUNTIME_DIR may not be set on all systems.

> I would have loved to get this boring chore off your shoulders but after trying
> for half an hour succumbed to my lack of C programming skills.

<3

> Also, I don't see any need to create a config path.
> ...
> Warpd should exit, however, if HOME is not set (as do most standard tools like cd).

Creating the parent directories seems like sane default behaviour. It makes it easier for the user to discover the path. There is some precedent for this, since several programs in the wild do this (e.g kitty).

**Comment by rvaiya** [comment]
> I agree with storing state in one location but looking at the most recent commit
> ...
>Many people have special backup policies for ~/.config, (personally, I don't want to
backup any logfiles on my laptop at all), 

Fair point. I hail from a time when men were men and dotfiles were dotfiles.  `~/.config/warpd` began life as `~/.warpd` before I cargo culted the (sporadically supported) XDG style.

I've eliminated the log file altogether (issues can still be debugged with -f) and moved the lock file to /tmp.

> On the other hand, an empty directory doesn't hurt anybody (at least not that much).

+1

I'm inclined to keep this behaviour.
