### ISSUE TITLE
MacOS M1，does not work

### ISSUE THREAD

**Issue by Fatpandac** [rvaiya/warpd#107]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/30423976/166550721-4ff4d553-7d4f-4389-a07d-a2c8f386f4ca.png">

**Comment by qyxtim** [comment]
This problem may be caused by the new update. I solve it by switching to the previous commit `133b8a2`.

**Comment by rvaiya** [comment]
Oops. This should be fixed in the latest commit.

**Comment by Fatpandac** [comment]
> This problem may be caused by the new update. I solve it by switching to the previous commit `133b8a2`.

Think you.

**Comment by rvaiya** [comment]
@Fatpandac To clarify, this shouldn't be necessary anymore.

**Comment by Fatpandac** [comment]
@rvaiya Yeah, it is solved on the latest commit, thx.
