### ISSUE TITLE
How to remapping shortcuts?

### ISSUE THREAD

**Issue by LintaoAmons** [rvaiya/warpd#108]
The default shortcut combination is so hard for me to hit. `A-M`

```
hint_activation_key		string		"A-M-x"			"Activates hint mode."
grid_activation_key		string		"A-M-g"			"Activates grid mode and allows for further manipulation of the pointer using the mapped keys."
screen_activation_key		string		"A-M-s"			"Activate (s)creen selection mode."
activation_key			string		"A-M-c"			"Activate normal movement mode (manual (c)ursor movement)."
hint_oneshot_key		string		"A-M-l"			"Activate hint mode and exit upon selection."
```

I want to change it to another combination, like `C-M` or something else, which is more fit for me.

Is there a way to achieve this?

**Comment by rvaiya** [comment]
Yes, you can rebind all keys in ~/.config/warpd/config. Please see the man page for more details.

**Comment by Hi-Angel** [comment]
@LintaoAmons did you ever get it working? I [stumbled upon rebinding via config do nothing](https://github.com/rvaiya/warpd/issues/308), and I'm wondering if there's perhaps some magic trick, or is it just buggy in the latest released version.

**Comment by LintaoAmons** [comment]
yeah, my is working:


```sh
~ on ☁️  (ap-northeast-1)
 cat ~/.config/warpd/config

hint_activation_key: A-M-j
activation_key: C-M-'
hint: f
exit: q
cursor_size: 13
```

**Comment by Hi-Angel** [comment]
@LintaoAmons what is your `warpd` version?
