### ISSUE TITLE
CLI Flag Specifying Alternative Config Path

### ISSUE THREAD

**Issue by p0da** [rvaiya/warpd#109]
Would you consider adding an additional CLI flag that allows users to specify a custom config path for that specific instance of warpd? This would be quite helpful especially when dealing with various oneshot binds. Thanks!

**Comment by rvaiya** [comment]
Can you elaborate on your use case? The last commit made warpd XDG
compliant so you can do XDG_CONFIG_HOME=/dir/ provided the config is
located at /dir/warpd/config.

**Comment by p0da** [comment]
Sure, so the goal is to enable different oneshot instances of warpd to have different bindings (for example a oneshot instance launched with a certain keybind may have its exit bound to "a" while a oneshot instance launced with a alternative keybind may have its exit bound to "b"). This can also be accomplished by specifying `XDG_CONFIG_HOME=/path/to/config warpd` but the addition of a CLI flag will make it much easier (and not require that the config file is named "config")

**Comment by rvaiya** [comment]
I've implemented this in the latest commit

**Comment by p0da** [comment]
Thanks!
