### ISSUE TITLE
feature request: configurable scroll speed and acceleration

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#112]
When reading about scrolling in our last discussion, I remembered the lack of configurable scroll speed and acceleration (it seems as if acceleration is used for scrolling as well) in warpd. This doesn't affect me personally as I either use (S-)space when browsing and my trackpoint or a scrollwheel on the thumbcluster of my keyboard otherwise, but certainly other users would benefit from it.

**Comment by rvaiya** [comment]
Implemented.
