### ISSUE TITLE
Add a systemd unit file?

### ISSUE THREAD

**Issue by Enter-tainer** [rvaiya/warpd#113]
It will be useful to run warpd as a daemon.

I've already written one and it works fine now.

```
❯ cat .config/systemd/user/warpd.service
[Unit]
Description=Warpd
After=graphical-session.target
PartOf=graphical-session.target

[Service]
Type=forking
ExecStart=/usr/bin/warpd
ExecStop=pkill warpd
ExecStop=rm /tmp/warpd_1000.lock

[Install]
WantedBy=graphical-session.target
```

**Comment by rvaiya** [comment]
Thanks for the suggestion, but I would rather  leave this up to the user (some people prefer to do everything in ~/.xinitrc) than ship a systemd file. Not every distro uses it, and the wayland version is run exclusively using flags anyway.
