### ISSUE TITLE
why not found cocoa?

### ISSUE THREAD

**Issue by luo10** [rvaiya/warpd#118]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/17287671/167595456-58f59886-affc-4607-b9ab-b488b61dcaca.png">

**Comment by luo10** [comment]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/17287671/167668917-237691b5-536a-4a47-886b-76fb535bba7b.png">
<img width="522" alt="image" src="https://user-images.githubusercontent.com/17287671/167669231-b90e842b-b02a-4bfa-9ef2-2daf727fe062.png">
i don't know what happen..

**Comment by rvaiya** [comment]
I've released macos binaries, so you shouldn't need to compile from source anymore. Please try the latest instructions in the readme.

**Comment by luo10** [comment]
thx bro.
