### ISSUE TITLE
Feature request: add a slow movement key

### ISSUE THREAD

**Issue by QiangF** [rvaiya/warpd#120]
There are needs to move cursor more precisely, such as data point extraction on a digital image. 

    slow_motion_speed: 5
    slow_motion_toggle_key: t

**Comment by QiangF** [comment]
The issue is“tap the movement key”moves several pixels currently, my current speed setting is 50. I think a slow motion speed like 5 will give pixel precise movements.

**Comment by rvaiya** [comment]
This was implemented and merged in 3683ce3. `d` (by default) can be used to reduce cursor speed.
