### ISSUE TITLE
display notification  message after the normal mode 

### ISSUE THREAD

**Issue by xtccc** [rvaiya/warpd#121]
I use the i3wm , so I always press the M-1 or M-2 or ... ,
and i set the activation_key to M-x 
When I enter normal mode, I am not sure if I am entering normal mode. I hope that there will be a notification prompt or where to display some message after entering normal mode.
I looked at the configuration file and it seems that this requirement is not supported.

**Comment by xtccc** [comment]
Thanks for your suggestion, I will try to configure oneshot's warpd in i3wm's config,

But I need more than a notifaction when  start the  normal mode,
Let me describe a scenario:
I enter normal mode, and after pressing scroll_down or scroll_up the warpd cursor disappears, I can't tell if I'm in warpd or i3wm, unless I press left or right or up or down again, the cursor will Again appear. 

in this scenario, I need to know if I'm in normal mode.

**Comment by xtccc** [comment]
> Another solution could be to unobtrusively draw a thin frame in some color around the screen,

I like the solution ,This solution sounds good

**Comment by rvaiya** [comment]
I've implemented an optional visual indicator in the latest commit. See the `indicator_*` options in the man page.
