### ISSUE TITLE
After scroll_up or scroll_down , I want to cursor still appear 

### ISSUE THREAD

**Issue by xtccc** [rvaiya/warpd#124]
After scroll_up or scroll_down , I want to cursor still appear 

I enter normal mode, and after pressing scroll_down or scroll_up the warpd cursor disappears, I can't tell if I'm in warpd or i3wm, unless I press left or right or up or down again, the cursor will Again appear.

**Comment by rvaiya** [comment]
The latest commit adds a small visual indicator (which you requested in #121) which persists while scrolling.

**Comment by xtccc** [comment]
I like the commit so much , thanks your code
