### ISSUE TITLE
Any hope of Gnome support on Wayland in the future?

### ISSUE THREAD

**Issue by draffensperger** [rvaiya/warpd#125]
Being a happy NeoVim users who likes easymotion, I was super excited to learn about `warpd`. It works well on X11 and Mac for me. 

However, my main desktop is going to be moving to GNOME on Wayland in the coming months (not totally up to me).

Is there potential for warpd to support GNOME on Wayland in the future? Or is this a fundamental technical limitation?

**Comment by rvaiya** [comment]
Unfortunately gnome doesn't support the requisite protocols. Even the limited support which exists for wayland has some fundamental limitations (though I hope to remedy some of these soon). It might be possible to implement something using gnome shell extensions, but I don't have the time or inclination for it. See also #54.

**Comment by draffensperger** [comment]
OK, thanks, that makes sense!

**Comment by Neyl-123** [comment]
Which protocols are not supported by GNOME? I'd like to use warpd and since I really like GNOME Shell (I'm on Fedora 37 and don't want to switch to sway or use X11) , I want to know what exactly the problem is and consider helping with the implementation to get it working.
