### ISSUE TITLE
Feature request: uninstall 

### ISSUE THREAD

**Issue by BIUBIULUOXX** [rvaiya/warpd#129]
Hi,

I am surprised to see such a good product and it really helps a lot :)
However, I wonder if there is a way to uninstall it, cuz the shortcuts seems conflicting with the shortcut from my other apps. It turns out to be messy. Could you plz tell me how to clean it up?

I executed commands below on macOS to install 

```
sudo curl -Lo /usr/local/bin/warpd https://github.com/rvaiya/warpd/releases/download/v1.2.2/warpd-osx && \
sudo chmod +x /usr/local/bin/warpd && \
sudo curl -Lo /usr/local/share/man/man1/warpd.1.gz https://github.com/rvaiya/warpd/releases/download/v1.2.2/warpd.1.gz
```
and tried to remove all the files.. 
```
uninstall:
	rm $(DESTDIR)$(PREFIX)/share/man/man1/warpd.1.gz\
		$(DESTDIR)$(PREFIX)/bin/warpd
```
but still did not work. Once I press opt+cmd+L, the screen is filled with letters.. and I suffer from intensive phobia that is reason I want to clean it up. please help me.

Regards,

Lassie

**Comment by rvaiya** [comment]
You can kill the process like any other unix daemon `pkill warpd`. If you want to remove it from your system just delete the installed files, e.g `rm /usr/local/bin/warpd /usr/local/share/man/man1/warpd.1.gz`
