### ISSUE TITLE
Suggestion: a method to reach "all" pixels in just three keystrokes

### ISSUE THREAD

**Issue by fboumol** [rvaiya/warpd#132]
Let me suggest a method to always reach everything in hint mode with just three keystrokes. It would be based in adding a new layer (this would be the 3rd keystroke) to your current hint mode; the 3rd keystroke would correspond to a selection with labels a,b,...,z (just one letter) inside the small region selected by the first 2 keystrokes.

The obvious problem is that nobody will be able to read such labels because they would be really tiny (and perhaps superpose among them). I think this would be solved using an _on-the-fly zoom of the small region_, like the following collage (all images correspond to the same background) suggest. In these images the labels a,b,...,z of the 3rd keystroke have not been included, but I guess you get an idea of what I mean.

![warpd-IdeaZoomUsingSlopShaders-20220609-collage](https://user-images.githubusercontent.com/10630557/172859350-5e8640a4-831f-4ae9-8623-1fb602987e1b.jpg)

The good news is that this zoom layer could be easily based (it is my guess, but I am not a programmer) on using the command [`slop`](https://github.com/naelstrof/slop) with a shader displaying the zoom of the small area not yet determined (but with extra labels a,b,...,z corresponding to the 3rd key). At the bottom of [slop homepage](https://github.com/naelstrof/slop) there is an example shader like a magnifying glass. This example is a circle based on [crosshair shader](https://github.com/naelstrof/slop/tree/master/shaderexamples), but for this particular aim you could use (with a small change of parameters) the [boxzoom shader](https://github.com/naelstrof/slop/tree/master/shaderexamples) which displays a box (i.e., a rectangle).

Let me clarify the _"algorithmic" steps_ of what I have in mind for this improved hint mode:
 - the first keystroke is done like up to now (so after this first keystroke we only see one column of labels with hints),
 - when one does the 2nd keystroke then it happens the following: all labels of the previously shown column are hidden, new labels (a,b,...,z) are added with really tiny font in the small matching region, and they are immediately displayed in its zoomed version (using slop with a shader). 
  
I also suggest that the display of labels among a,b,...,z (arranged in rows and columns) in this small region follows the usual alphabetical order with one exception. _The exception  would be_ that the letter in "the origin (i.e., center) of coordinates of the zoomed area" must always be the very letter used in the second keystroke. For example, if the first two keystrokes are `i` + `m` then in the center of the zoomed region put the letter `m`. The reason to do so is that if you know in advance that you do not need the 3rd keystroke then it would be enough to press the 2nd keystroke twice (which is always fast).

Do you think this makes sense?

**Comment by rvaiya** [comment]
> Let me suggest a method to always reach everything in hint mode with just three keystrokes.
> [...]

A similar idea has been proposed in #100. I plan on adding something like this when I have some time. 

> The obvious problem is that nobody will be able to read such labels because
they would be really tiny (and perhaps superpose among them).

I'm less keen on the magnification idea, implementation issues aside, UI elements should generally be smaller than hints (you may need to adjust your hint size). Additionally, it should already
be possible to select almost any element on the screen within 2-4 keystrokes (this is discussed at length in #100);

> The good news is that this zoom layer could be easily based (it is my guess,
> but I am not a programmer) on using the command slop with a shader displaying
> the zoom of the small area not yet determined (but with extra labels a,b,...,z
> corresponding to the 3rd key).

This looks like an interesting project. Unfortunately it isn't fully cross platform and would involve pulling in a bunch of dependencies. I currently don't intend on adding magnification anyway.

> Let me clarify the "algorithmic" steps of what I have in mind for this improved
> [...]

This is similar to what I have in mind (sans magnification), though I think its utility is being overestimated and you may just need to tweak your hint settings.

> The exception would be that the letter in "the origin (i.e., center) of coordinates of the zoomed area" must always be the very letter used in the second keystroke.

This is an interesting optimization I hadn't considered, though it would make memorizing relative positions of the second grid impossible.

I'm closing this in favour of #100. Feel free to respond in that thread.
