### ISSUE TITLE
Hints get drawn below the pop-up menus

### ISSUE THREAD

**Issue by janmejay** [rvaiya/warpd#134]
This prevents working with pop-up menus (such as items accessible thru right click) difficult.

![screenshot-20220613@114602](https://user-images.githubusercontent.com/12777/173291605-e0f11342-5db5-474a-98ff-7a2f62f44ab6.png)

**Comment by rvaiya** [comment]
I can't seem to reproduce this. What window manager/app are you using?

**Comment by janmejay** [comment]
`xorg-xserver` 21.1.3-r2

**Comment by janmejay** [comment]
@rvaiya about this one, if avoid using cached-hints it draws hints above the pop-up menus. 
```
┌(pts/12) janmejay at js in ~/projects/warpd on master! [ Wed 22  8:05PM ]
└(10014) (Gentoo) ±➤ git diff
diff --git a/src/platform/X/hint.c b/src/platform/X/hint.c
index 04ea2dd..44cec78 100644
--- a/src/platform/X/hint.c
+++ b/src/platform/X/hint.c
@@ -155,7 +155,7 @@ void hint_draw(struct screen *scr, struct hint *hints, size_t n)
    XMoveWindow(dpy, scr->cached_hintwin, -1E6, -1E6);

    /* Use the cached window, if it exists. */
-   if (n == scr->nr_cached_hints &&
+   if (0 && n == scr->nr_cached_hints &&
        !memcmp(scr->cached_hints, hints, sizeof(struct hint) * n)) {
        GC gc = XCreateGC(dpy, DefaultRootWindow(dpy),
                   GCForeground | GCFillStyle,

┌(pts/12) janmejay at js in ~/projects/warpd on master! [ Wed 22  8:06PM ]
└(10016) (Gentoo) ±➤
```
![screenshot-20220622@200743](https://user-images.githubusercontent.com/12777/175057091-2ad99af9-3c87-416a-a4e0-5cbcd6a11966.png)

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit.
