### ISSUE TITLE
Sway (wayland) cursor offset

### ISSUE THREAD

**Issue by yellowhat** [rvaiya/warpd#135]
Hi,
I have just installed `warpd` on [Fedora 36](https://copr.fedorainfracloud.org/coprs/yellowhat/yellowhat/package/warpd/) with Sway (`xwayland disable`).

I have added the following to `config`:
```
bindsym Mod4+Mod1+x exec warpd --hint
bindsym Mod4+b exec warpd --normal
bindsym Mod4+g exec warpd --grid
```
If I press `Mod4+b` an orange square appears on the middle of the screen. I can move it with `h`, `j`, `k`, `l`, interestingly the "real" cursor moves but does not overlap with the square.
If I press `m` it left click on the "real" cursor position. 

If I press `Mod4+g` the grid appears. I can slice it using `u`, `i`, `j`, `k`, I have noticed that as I slice the "real" cursor moves. 
Again if I press `m` it left click on the "real" cursor position. 

If I run from terminal:

```bash
$ warpd -f --grid
wayland: init_hint unimplemented
wayland: mouse hiding not implemented
```

Interestingly I have noticed that, just after I press for the first time the key `h` or `j` or `k` or `l` (on `Mod4+...` nothing changes), it moves the "real" cursor to a constant offsetted position to the square cursor. 
For example: let assume the cursor is here:

```
+---------------+
|               |
|               |
|               |
|               |
|  x            |
|               |
+---------------|
```

before I press any `warpd` trigger combination.
I press `Mod4+b` nothing changes:

```
+---------------+
|               |
|               |
|               |
|               |
|  x            |
|               |
+---------------|
```

Just after I press any `h`, `k`, `l`, `l`, `u`, `i` it is moved here:

```
+---------------+
|               |
|    x          |
|               |
|      O        |
|               |
|               |
+---------------|
```
On the next press the offset remains constant.

```
+---------------+
|               |
|     x         |
|               |
|       O       |
|               |
|               |
+---------------|
```

Any ideas?

Thanks

**Comment by rvaiya** [comment]
Did you compile with `PLATFORM=wayland`? How many screens do you have?

**Comment by yellowhat** [comment]
Yes I have used `PLATFORM=wayland`.
I have 3 monitors (laptop + 2 external):

```
output DP-3 resolution 3840x2160 scale 1.5
output DP-2 resolution 3840x2160 scale 1.5 transform 270

output DP-3 pos     0    0
output DP-2 pos -1440 -720
```

**Comment by rvaiya** [comment]
I don't have a multi monitor setup at the moment. Can you see if the problem disappears when you use a single screen?

**Comment by yellowhat** [comment]
I have tried on another laptop: single screen, `scale  1.0`, and I do not have any problems.
May it is related to the fact that I am using `scale != 1.0` and `transform`?

**Comment by rvaiya** [comment]
It's probably a bug in the logic used to obtain wayland screen geometry. I believe the protocol used (`xdg-output`) should account for any transformations, but I will have to investigate when I have some time.

**Comment by yellowhat** [comment]
Sure, thank you very much

**Comment by rvaiya** [comment]
Can you try the latest commit?

**Comment by yellowhat** [comment]
Yes, it works as expected now.
Thank you very much

**Comment by krobelus** [comment]
If I enable only my laptop monitor or monitors, it works now.

	$ swaymsg -t get_outputs
	Output HDMI-A-2 'Unknown Paperlike H D 0x00000000' (focused)
	  Current mode: 2200x1650 @ 40.001 Hz
	  Position: 0,1440
	  Scale factor: 1.400000
	  Scale filter: linear
	  Subpixel hinting: unknown
	  Transform: normal
	  Workspace: 1
	  Max render time: off
	  Adaptive sync: disabled
	  Available modes:
	    2200x1650 @ 40.001 Hz
	    1600x1200 @ 60.000 Hz

	Output eDP-1 'Panasonic Industry Company 0x96A2 0x00000000'
	  Current mode: 2560x1440 @ 59.999 Hz
	  Position: 0,0
	  Scale factor: 1.000000
	  Scale filter: nearest
	  Subpixel hinting: unknown
	  Transform: normal
	  Workspace: 5
	  Max render time: off
	  Adaptive sync: disabled
	  Available modes:
	    2560x1440 @ 59.999 Hz

but if I switch off my laptop monitor, I get a similar issue.

	Output HDMI-A-2 'Unknown Paperlike H D 0x00000000' (focused)
	  Current mode: 2200x1650 @ 40.001 Hz
	  Position: 0,1440
	  Scale factor: 1.400000
	  Scale filter: linear
	  Subpixel hinting: unknown
	  Transform: normal
	  Workspace: 1
	  Max render time: off
	  Adaptive sync: disabled
	  Available modes:
	    2200x1650 @ 40.001 Hz
	    1600x1200 @ 60.000 Hz

	Output eDP-1 'Panasonic Industry Company 0x96A2 0x00000000' (inactive)
	  Available modes:
	    2560x1440 @ 59.999 Hz

**Comment by rvaiya** [comment]
@krobelus 

This is because you still have your second screen at offset `0x1440` in the global coordinate space after disabling your first screen. Wayland lets you do this for reasons I have not been able to divine. 

You can either reposition it to the origin using something like `swaymsg output HDMI-A-2 pos 0 0` or you can disable the first screen using `swaymsg output eDP-1 dpms off`, which will just turn the screen off without affecting geometry. 

It might be possible to account for this sort of pathological case within warpd by performing the same gymnastics as the compositor, but having an inconsistent screen layout probably has implications for other tools and as far (as I can tell) should probably be regarded as user error.

**Comment by krobelus** [comment]
On Sun, Jun 26, 2022 at 08:27:47PM -0700, rvaiya wrote:
> @krobelus 
> 
> This is because you still have your second screen at offset `0x1440` in
> the global coordinate space after disabling your first screen. Wayland
> lets you do this for reasons I have not been able to divine.
> 
> You can either reposition it to the origin using something like `swaymsg
> output HDMI-A-2 pos 0 0` or you can disable the first screen using
> `swaymsg output eDP-1 dpms off`, which will just turn the screen off
> without affecting geometry.
> 
> It might be possible to account for this sort of pathological case within
> warpd by performing the same gymnastics as the compositor, but having an
> inconsistent screen layout probably has implications for other tools and
> as far (as I can tell) should probably be regarded as user error.

got it, thanks. If anything sway should probably make it harder to create this weird state

Thanks for this tool BTW, I was using mouse keys on my Ducky keyboard before but a software solution is more powerful.
