### ISSUE TITLE
hint bachground on sway

### ISSUE THREAD

**Issue by DNDEBUG** [rvaiya/warpd#136]
How do i stop this?
![20220617_16h58m28s_grim](https://user-images.githubusercontent.com/98880063/174393670-778c5645-0c5f-44ff-8c91-6ab8e895d126.png)

**Comment by rvaiya** [comment]
Did you compile with `PLATFORM=wayland`? What does your config look like?

**Comment by rvaiya** [comment]
In the readme my dear fellow, in the readme ;).
