### ISSUE TITLE
Fonts on Sway

### ISSUE THREAD

**Issue by DNDEBUG** [rvaiya/warpd#137]
i'm trying to use unifont
```hint_font: unifont``` and ```hint_font: Unifont``` aren't working
no fonts are working, i can't change the default one

**Comment by rvaiya** [comment]
font is currently not configurable on wayland. I'll release a patch for
this when I have some time, but be aware wayland is generally not well
supported and has several warts.

**Comment by rvaiya** [comment]
This should work in the latest commit.
