### ISSUE TITLE
different location for history file (outside configuration directory)

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#139]
Could the history file please be saved outside the configuration directory? I think that `$XDG_DATA_HOME/warpd` with `$XDG_DATA_HOME` defaulting to `$HOME/.local/share` (or the equivalent on mac) is a much better choice, for the same reasons as last time we discussed about file locations.

PS: I'm sure that you saw this request coming...

**Comment by rvaiya** [comment]
Though history is technically state, I think it is close enough to configuration to warrant keeping them together. If more state begins to accrete (unlikely) I might consider making use of the other `XDG_*` directories.

**Comment by rvaiya** [comment]
I've reconsidered and implemented this in the latest commit.
