### ISSUE TITLE
[Wayland] The initial value of the mouse pointer in warpd normal mode is the current mouse pointer position

### ISSUE THREAD

**Issue by tkna91** [rvaiya/warpd#142]
Thanks for your cool project.

I think it would be easier to perform consecutive operations if the current mouse pointer position is the initial value of the warpd normal mode mouse pointer.
The current version, which starts operations from the center of the screen, would be fine by default, but in that case, it would be nice to have the above as an option.
I would appreciate your consideration.

Sorry if I am saying something strange.

**Comment by tkna91** [comment]
@herrsimon Yes, I am using Wayland (sway).
Could it be that Wayland cannot get the mouse pointer position? Is this behavior inevitable?

https://user-images.githubusercontent.com/102382754/177054787-53d9a3aa-0f55-4e16-b4c1-29c8c9fba55f.mp4

**Comment by tkna91** [comment]
I see, I will wait.
@rvaiya, I know it may be a lot of work, but if you feel up to it, please do.
@herrsimon Thanks for your kindness.

**Comment by rvaiya** [comment]
At the moment I don't believe this is possible. As far as I know, there isn't a way to obtain pointer coordinates, so warpd has to keep track of them internally. Having said that, I haven't plumbed the depths of some of the newer protocols, though I imagine this sort of thing might be considered a security risk by the wayland folks. 

Getting warpd to its present state of functionality on wayland already required abusing some of the experimental protocols.

> EDIT: [this](https://wayland.freedesktop.org/libinput/doc/latest/api/group__event__pointer.html) looks promising.

warpd doesn't have direct access to the input devices, so it can't make use of any libinput functionality.

**Comment by rvaiya** [comment]
>  Could a (very ugly) solution be to call warpd from a wrapper script with setuid root or any other sufficiently privileged user, which queries global pointer coordinates and passes them as options to the warpd call?

My understanding is that the compositor is the only component which keeps track of cursor position. Even if you had root access you would need some way to query the internal state of the compositor. X provides an API mechanism for this, I believe wayland does not (for security reasons).

**Comment by rvaiya** [comment]
That approach is a bit ham fisted and probably quite expensive. I don't know if the end result would be usable and it would require some non trivial changes to the wayland platform code. PRs are welcome if someone wants to invest the effort and is able to produce something usable.

**Comment by tkna91** [comment]
After doing `slurp -p`, I did `leftmouse` with keyd and got the coordinates. How about this?
- https://man.archlinux.org/man/slurp.1
- https://github.com/emersion/slurp

https://user-images.githubusercontent.com/102382754/177866267-a66a0084-95c3-45cc-a3d1-489cf6723bdd.mp4

**Comment by rvaiya** [comment]
Thanks.

A cursory look at the code would suggest slurp is using a similar trick to the one you described. Namely creating a large transparent surface and then extracting coordinates (using API calls rather than image analysis). 

It should be possible to employ a similar technique in warpd, but I don't have time at the moment. There are a number of other issues with the wayland implementation of warpd that I hope to remedy in my keyd port, and to which I am more inclined to direct effort. PRs are welcome in the meantime.

**Comment by tkna91** [comment]
It seems that ydotool can manipulate the mouse pointer in relative coordinates
https://github.com/ReimuNotMoe/ydotool

```
# Relatively move mouse pointer to -100,100:

ydotool mousemove -- -100 100
```
Maybe there is a way to figure out the current coordinates of the mouse pointer or a way to directly move the relative position of the mouse pointer. Sorry if I am missing the point.

Commands executed
```
# ydotoold &
```

/etc/keyd/test.conf
```
[ids]
*

[main]
tab = overload(TAB, tab)

[TAB]
j = command(ydotool mousemove --  0 -10)
k = command(ydotool mousemove --  0  10)
h = command(ydotool mousemove -- -10  0)
l = command(ydotool mousemove --  10  0)
```

https://user-images.githubusercontent.com/102382754/186562742-0f79dd59-7afb-44ae-9378-9772744a0dde.mp4

**Comment by rvaiya** [comment]
The internal platform API (and many core features) is designed around being able to query cursor position.  Relative movement is insufficient, the correct way to achieve this is probably to take the slurp approach. I just don't have time at the moment.

**Comment by roland-rollo** [comment]
@rvaiya is this somehow helpful? https://github.com/flatpak/xdg-desktop-portal/pull/711

**Comment by rvaiya** [comment]
@roland-rollo 

I don't believe that is relevant. As I understand it, that is a new dbus protocol to allow for things like global key bindings that isn't universally supported. As I mentioned in my last post, this should be possible to achieve using native wayland protocols, I just haven't had the time to implement it.

**Comment by rvaiya** [comment]
I decided to invest some time on this since a keyd implementation is some time off and this seems to be a perennial issue. The latest commit should include a fix. I would appreciate it if someone with multiple screens could test this, as I don't have a multi head setup at the moment.

**Comment by tkna91** [comment]
I checked in a multi-display environment.
The pointer's starting point in normal mode appears to be fine!
thanks!
```
$ paru -Q warpd-wayland-git
warpd-wayland-git r205.731f533-1
$
```

https://user-images.githubusercontent.com/102382754/194062826-04c72bea-8179-4627-9f6d-e9a9d06d4f15.mp4

**Comment by rvaiya** [comment]
Thanks for the confirmation.
