### ISSUE TITLE
should pressed buttons really be passed via exit codes?

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#145]
I just wrote some scripts to make use of warpd's recent improvements and would like to discuss whether it is truly a good idea to indicate the pressed mouse button via exit codes. When you first introduced it, I didn't think about the consequences, but now, when writing actual scripts, extracting the mouse button from the exit code doesn't feel right. At the moment, I can only find arguments against it:

- traditionally, non-zero exit codes indicate failure of some sort and the actual number specifies the type of failure.
- it is no longer possible to distinguish regular exit from a true failure, resulting in less robust scripts
- the exit code 1 is the default value for `EXIT_FAILURE` and also outside of C (most notably in common linux shells) typically represents some generic error
- I know no other programs which use exit codes for passing non-exit related information

Wouldn't it be a better idea to print button presses together with point coordinates as a third field (empty if the exit occured without button press, as when using `--hint --oneshot`), resulting in ouput like `812 341 1` for mouse key 1? Shell scripts could then simply use this third field if needed.

If you agree to this change, I could deal with this trivial and very boring chore to take some burden off your shoulders (already feel bad since for quite some time now, all I'm doing is continually writing feature request after feature request, without contributing anything).

**Comment by rvaiya** [comment]
> should have read the code properly before complaining

I probably should have documented it better. I've added a note in the man page.

> As written in the other issue, the obvious solution would be to print the print key itself, which enables advanced scripting logic. 

I can't think of any reason this would be useful. If you think it would allow for something which is currently not possible feel free to follow up in another issue.

> Another thing which would be interesting to know for scripts is whether the user aborted the operation by pressing an exit key.

If `--oneshot` is used, the exit status will be 0 if the user aborts the operation.

I'm closing this for now. Feel free to reopen it or follow up in your other threads.
