### ISSUE TITLE
Feature Request: Specify particular modifier key for bindings

### ISSUE THREAD

**Issue by vg250156** [rvaiya/warpd#158]
Hi, I have most of my OS level keymaps on Mod3, was wondering if it would be possible to make it so I could specify Mod3+x as my activation key.

**Comment by rvaiya** [comment]
Unfortunately this is unsupported for historical reasons have to do with the implementation of warpd's input layer. The current advice is to use something like [keyd](https://github.com/rvaiya/keyd) to generate the requisite activation strokes.

**Comment by vg250156** [comment]
Thanks
