### ISSUE TITLE
`git clone` requires authentication

### ISSUE THREAD

**Issue by Kabouik** [rvaiya/warpd#159]
I love `warpd` and wanted to try making a package file for Guix System (no promises, I'm a Guix newbie), but cloning the repository seems to require authentication. This is the only Github repository that does that on my machine (I tried several to see if that was a local issue with my `git config`).

I have `warpd` installed on another machine since a long time but that was around when you announced it on Reddit, quite some time ago, and didn't keep my local repository up to date until now. I tried cloning on that machine as well, and got the same issue.

**Comment by Kabouik** [comment]
This was me being a potato, sorry for the noise.

**Comment by rvaiya** [comment]
No worries. Thanks for taking the time to create a package.
