### ISSUE TITLE
feature request:exclude keys/key-bindings

### ISSUE THREAD

**Issue by chichow5** [rvaiya/warpd#161]
For example, sometimes I manage windows, but I need to exit the program to use <kbd>Alt</kbd>+<kbd>Tab</kbd>. I mean, leave some keys/key-bindings to the OS.

**Comment by rvaiya** [comment]
This has been requested before. Implementing in a platform agnostic way is non-trivial, so it is not on the horizon. Current efforts are being directed toward integrating similar functionality into [keyd](https://github.com/rvaiya/keyd).
