### ISSUE TITLE
improvement: Skip superfluous disambiguation step for duplicate hint labels

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#166]
When duplicate labels are fed to warpd using `--query`, the latest should be given preference, i.e. `echo "a 100 100\na 100 200\n" | warpd --query` should output coordinates (100, 200) upon pressing a. Currently, there is a disambiguation step (after pressing a, one has to press a again before any output appears), which makes little sense in this context.

Background: Motivated by #165, I tried to implement the regular hint mode in a way where only one letter is shown in each step. When feeding the hints for column selection (with duplicate labels) to `warpd --query`, I noticed the above issue.

**Comment by rvaiya** [comment]
The behaviour is undefined since duplicate labels are unsupported. Unique labels should be used since the user has no way of knowing which label the script emitted last (this is an implementation detail).
