### ISSUE TITLE
Feature Requet: Scrolling

### ISSUE THREAD

**Issue by TheZombie1999** [rvaiya/warpd#167]
It would be really nice if you could implement some way of using the mouse wheel.

Because this is the main limitation I encountered when using your Software.

Maybe you could use shift h,j,k,l to scroll in the desired direction.

**Comment by liushuai05** [comment]
> This is already supported, see `warpd --list-options | grep scroll`. Please close this issue.

Hello, warpd is really a useful tool, but I only see command results scrolling up and down. There's no way to roll left and right
