### ISSUE TITLE
Space as button key

### ISSUE THREAD

**Issue by BeCracked** [rvaiya/warpd#176]
Hello, I am trying to set space bar as the mouse button. Adding `buttons: m , . Space` to my config gives an error message `ERROR: Space is not a valid key name`. Using a lower case `space` does not throw an error message. However in grid mode pressing space ends grid mode and goes into normal mode but does not perform a click. In normal mode space also does not perform a click but, when on a browser window scrolls. When the config line is not present pressing space does nothing.

Is this expected?

**Comment by rvaiya** [comment]
You have an extraneous comma. Key names should be separate by spaces, so you want `buttons: m . space`. Also note that you've mapped `space` to right click.

**Comment by BeCracked** [comment]
I did take the `buttons: m , .` straight from the `--list-options`. I did however not properly read it as I didn't get that this was a mapping of all mouse buttons. I expected it to be just a list of keys I wanted to map to left click. This makes more sense now. With `buttons: space , .` it works exactly as intended. Thank you!
