### ISSUE TITLE
Feature Request: allow mode reactivation without ESC

### ISSUE THREAD

**Issue by eokic** [rvaiya/warpd#179]
In a scenario where I activate the Hint mode, I then position the cursor somewhere and press "m" to click. The mouse remains pending, waiting for further input. 

In this scenario, I wish to quickly activate that same positioning mode again but I cannot do so by simply pressing `A-M-x`, I **have to** press Esc for some reason which is at the other end of the keyboard. Why is this step necessary? Why can't `A-M-x` in a sense trigger the Esc key automatically for me?

I assume this suggestion applies to all modes, even though I'm primarily interested in the Hint mode.

Mac Studio (2022)
macOS 12.6 (21G115)

**Comment by kl** [comment]
You can simply press `x` to bring up hint mode again

**Comment by eokic** [comment]
That works perfectly, thanks! I've read through the docs but I haven't been able to find this info.
