### ISSUE TITLE
Using a screen in portrait mode results in hint boxes that are very narrow

### ISSUE THREAD

**Issue by justuswilhelm** [rvaiya/warpd#186]
I am on
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

using warpd 1.3.4 and I am attaching a screenshot of how it looks like:

![Screenshot from 2022-10-18 14-24-58](https://user-images.githubusercontent.com/1641042/196343196-d722642c-2894-42ed-8517-bae9e06bfe54.png)

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit.
