### ISSUE TITLE
toggle_drag is hardwired to first mouse button

### ISSUE THREAD

**Issue by justuswilhelm** [rvaiya/warpd#187]
I use my ambidextrous Logitech M110 left-handed. Therefore, I have remapped my Xmodmap as follows:

```
pointer = 3 2 1 5 4 6 7 8 9 10
```

Now, if I try to drag inside warpd, it will try to drag with a right click. I have fixed this temporarily by changing the code in toggle_drag as follows:

```
diff --git a/src/warpd.c b/src/warpd.c
index 3f5f2cd..515be21 100644
--- a/src/warpd.c
+++ b/src/warpd.c
@@ -13,9 +13,9 @@ void toggle_drag()
 	dragging = !dragging;
 
 	if (dragging)
-		platform_mouse_down(1);
+		platform_mouse_down(3);
 	else
-		platform_mouse_up(1);
+		platform_mouse_up(3);
 }
 
 static int mode_flag = 0;

```

The issue is that this will break the code for everyone else who is using their mouse in a regular way. It would be great if this can be configured instead using a config variable.

**Comment by rvaiya** [comment]
You can just remap the buttons, e.g `buttons: . , m`. See `--list-options` for a full list of options.

**Comment by rvaiya** [comment]
I've added a new option called `drag_button` which should address this.
