### ISSUE TITLE
Feature Request: Some more ideas!

### ISSUE THREAD

**Issue by matheusfillipe** [rvaiya/warpd#19]
First of all thanks a lot, I love this project so much and the scroll functionality and the hints customization is just like I dreamed! You did a really great job. 

Here are some ideas that I am still missing. Sorry if I am just saying something that is already implemented but I didn't find yet

1. Use multiple control keys in shortcuts. e.g. I really need something like M-A-w  M-A-s for the scroll because  the rest is taken :P. Just alt+character is kinda taken by most qt applications and useful for keyboard navigation on those. Maybe the default should even change to something like that but the point is having multiple hold keys on any those shortcuts.

2. Faster and slower movements in the "visual mode" of the discrete mode (dragging). Like S-j (S + any of hjkl) for faster up movement and so on. Could be someone like w and b in vim too but like jumping faster, but would be nice to have it up and down too. So we would have the movement_increment option and the fast_movement_increment for the discrete mode.

3. Multiple shortcuts for the same function. This is the least important but like for the discrete_beginning I sometimes use S-backslash (which is the pipe simbol '|') but also 0, and both are the vim default shortcuts. Would it be hard to have something like: discrete_beginning: S-backslash, S-6?

That is all, I can throw my mouse in the trashcan already if 1 and 2 happens :P.

**Comment by rvaiya** [comment]
> Use multiple control keys in shortcuts. e.g. I really need something like M-A-w
M-A-s for the scroll because the rest is taken :P. Just alt+character is kinda taken by most qt applications and useful for keyboard navigation on those.  Maybe the default should even change to something like that but the point is having multiple hold keys on any those shortcuts.

This should already be possible by setting `scroll_up_key` to `M-S-a`.

> Faster and slower movements in the "visual mode" of the discrete mode
(dragging). Like S-j (S + any of hjkl) for faster up movement and so on. Could be someone like w and b in vim too but like jumping faster, but would be nice to have it up and down too. So we would have the movement_increment option and the fast_movement_increment for the discrete mode.

I have been considering adding 'word operators' of configurable widths.  You can already do something like 20j in discrete mode to move 20 units down, but you should be using hint or grid mode for long distance movements anyway. 

> Multiple shortcuts for the same function. This is the least important but like
for the discrete_beginning I sometimes use S-backslash (which is the pipe simbol '|') but also 0, and both are the vim default shortcuts. Would it be hard to have something like: discrete_beginning: S-backslash, S-6?

For consistency I would have to add this to every option which I am too lazy to do at the moment :P. It is probably a good idea to adjust your muscle memory anyway in order to remind yourself that you aren't in vim and that the unit keys correspond to movement rather than lines of text. If you still want this in a week I will consider adding it. I usually select a paragraph of text by using visual mode in conjunction with hint mode.

**Comment by matheusfillipe** [comment]
> This should already be possible by setting `scroll_up_key` to `M-S-a`.

The latest warpd gives me "invalid entry at line" on the line I use M-S-a. Did you mean M-S-a for "Alt+Meta+w" ? Doesn't S means shift? Or am I getting this totally wrong.

> I have been considering adding 'word operators' of configurable widths. You can already do something like 20j in discrete mode to move 20 units down, but you should be using hint or grid mode for long distance movements anyway.

I agree that hints mode is for long distances but sometimes if you set a lower number of hints (maybe because you are too blind and need huge ones, which is my case :P)  would be nice to have a little faster discrete movement just for "walking on that hint area" and is a nice feature to have for discrete mode itself anyway. Would be like word operators but i think shift+(hjkl) would fit perfect... but those are just configurable per user anyway.

> For consistency I would have to add this to every option which I am too lazy to do at the moment :P. It is probably a good idea to adjust your muscle memory anyway in order to remind yourself that you aren't in vim and that the unit keys correspond to movement rather than lines of text. If you still want this in a week I will consider adding it. I usually select a paragraph of text by using visual mode in conjunction with hint mode.

Well no pressure at all on that one. I care about 1 and 2 much more.

**Comment by rvaiya** [comment]
This should already be possible by setting scroll_up_key to M-S-a.

> The latest warpd gives me "invalid entry at line" on the line I use M-S-a. Did you mean M-S-a for "Alt+Meta+w" ? Doesn't S means shift? Or am I getting this totally wrong.

Sorry, you're right it should be `M-A-w`. `M-S-a` is meta+shift+a (which should work). The following in your `~/.warprc` should produce the desired results:

```
scroll_down_key: M-A-w
scroll_up_key: M-A-d
```

> I agree that hints mode is for long distances but sometimes if you set a lower number of hints (maybe because you are too blind and need huge ones, which is my case :P) would be nice to have a little faster discrete movement just for "walking on that hint area" and is a nice feature to have for discrete mode itself anyway. Would be like word operators but i think shift+(hjkl) would fit perfect... but those are just configurable per user anyway. Also sometimes we need extra precision so I'd like to leave the default hjkl much slower.

I'll consider adding something like this when I have some time. You might want to consider changing the hint color. I can fit nearly 1000 hints (`hint_characters: abcdefghijklmnopqrstuvwxyz;'/.`) on my 14" laptop screen quite comfortably and my eyesight isn't great.

**Comment by matheusfillipe** [comment]
> This should already be possible by setting scroll_up_key to M-S-a.

Oh! you were totally right all the time, I actually had something bound to this combination already :P

> I'll consider adding something like this when I have some time. You might want to consider changing the hint color. I can fit nearly 1000 hints (hint_characters: abcdefghijklmnopqrstuvwxyz;'/.) on my 14" laptop screen quite comfortably and my eyesight isn't great.

Thanks! Nah... as I said this is something I really want... Basically having a fast and slow move for more precision, if you want to think as this.

**Comment by rvaiya** [comment]
Word based movement has been implemented in the latest commit. The default bindings are vi-like (w, b, etc) but you can use something like

```
discrete_word_left_word: S-h
discrete_word_right_word: S-l
discrete_word_up_word: S-k
discrete_word_down_word: S-J
```

to achieve the effect you want.

**Comment by rvaiya** [comment]
Looks like I forgot to push the last commit :P. It should be available now.

**Comment by matheusfillipe** [comment]
> Looks like I forgot to push the last commit :P. It should be available now.

Haha I realized that! It can Happen.

Working like a charm! What I did to be more vim like was:
```
discrete_home: g
discrete_last: S-g
discrete_left_word: S-h
discrete_right_word: S-l
discrete_up_word: S-k
discrete_down_word: S-j
discrete_beginning: S-backslash
```
The discrete_word_size of 80 by default just worked really great for me as well.

But yeah the project just got extremely configurable and suitable for any user with this I think! When we have multiple shortcuts for the same command you will really be able to do anything :P.


I was taking a look on cfg.opts and there is this weird line:

`
6  buttons                   string  "m,comma,period,x,c"    "The number of columns in the grid."
`

Which are the mouse buttons I suppose? What would x and c be for? I was thinking, actually forgot to mention when I opened this that another cool feature that might be not so hard to implement is to have "y" as a shortcut for copy instead of having to hit "m" and then ctrl+c. We could have something like y for ctrl+c and Y (S-y) for ctl+shift+c for terminals compatibility. Or emulating keypresses is out of the scope of this project since we are just emulating the mouse here? Well is just and idea.

**Comment by rvaiya** [comment]
> I was taking a look on cfg.opts and there is this weird line:

Thanks for spotting that. It is a documentation error. Those are indeed the mouse buttons, x and c correspond to mouse buttons 4 and 5 which are considered scroll events in X. You can use them in discrete mode to scroll. I have amended the documentation accordingly.

> I was thinking, actually forgot to mention when I opened this that another cool feature that might be not so hard to implement is to have "y" as a shortcut for copy instead of having to hit "m" and then ctrl+c. We could have something like y for ctrl+c and Y (S-y) for ctl+shift+c for terminals compatibility. Or emulating keypresses is out of the scope of this project since we are just emulating the mouse here? Well is just and idea.

I've considered this but decided against it given that C-c is not standardized across the linux desktop.  I've also considered adding arbitrarily configurable key combinations but ultimately decided it was beyond the scope of the project. C-c is not too much of an encumbrance to hit and not necessary for many applications (simply selecting text in urxvt for instance automatically copies it to the primary clipboard).

**Comment by matheusfillipe** [comment]
> I've considered this but decided against it given that C-c is not standardized across the linux desktop. I've also considered adding arbitrarily configurable key combinations but ultimately decided it was beyond the scope of the project. C-c is not too much of an encumbrance to hit and not necessary for many applications (simply selecting text in urxvt for instance automatically copies it to the primary clipboard).

It makes sense.

**Comment by rvaiya** [comment]
I am closing this. In the future please create a separate issue for each request.
