### ISSUE TITLE
deceleration ceases to take effect

### ISSUE THREAD

**Issue by OSS542** [rvaiya/warpd#192]
deceleration ceases to take effect if currently held motion button is released and another is pressed while still holding deceleration key.

**Comment by OSS542** [comment]
#191 is different and not a duplicate of #192 in that for #191 deceleration does not take effect at all if the decelerator key is held first.  It must be pressed after the motion key.
In the case of #192 deceleration occurs but stops if the currently held motion button is released and another is pressed without releasing the deceleration key.

**Comment by OSS542** [comment]
If deceleration could be maintained as long as the deceleration key is held, it becomes possible to change direction while temporarily maintaining a slow speed.

**Comment by rvaiya** [comment]
Can you clarify what you mean by 'motion key'? The sequence `<d down> <h down> <h up> <l down>` should work as expected (reduce cursor speed throughout). The only potential issue if you try and simultaneously depress the accelerator and decelerator key.

**Comment by OSS542** [comment]
I have checked #191 and #192 again, and it seems to be working for me at the moment.  I am no longer able to recreate the problem for #191 and #192.  I will close #192 and file a new issue if I can recreate it in the future.
