### ISSUE TITLE
hard lockout if screen locker is used with warpd active

### ISSUE THREAD

**Issue by OSS542** [rvaiya/warpd#194]
Warpd does not permit screen lockers to accept a password if warpd is active.   It is necessary to  terminate warpd by logging in remotely via another machine.

**Comment by rvaiya** [comment]
What platform/version (`warpd -v`) are you using?

**Comment by OSS542** [comment]
Linux  5.7.0  SMP  x86_64 GNU/Linux
custom distribution built entirely from source code
warpd 1.3.3

**Comment by rvaiya** [comment]
Are you running the latest commit? (what is the full output of `warpd -v`). What compositor/DE are you using?

**Comment by OSS542** [comment]
running the 1.3.3 release, not the latest commit.  Using i3 tiling window manager directly over X11 root window.

**Comment by OSS542** [comment]
note: the screen locker is i3lock.

**Comment by rvaiya** [comment]
To clarify, are you suggesting that the locker becomes unresponsive while warpd is *active* (in one of its modes) or simply while it is running? If it is the former, this is par for the course (assuming your locker uses xinput). How are you triggering this bug?

**Comment by OSS542** [comment]
This can happen while warpd is active.  The locker is unable to receive keystrokes to unlock the display.  If the user fails to deactivate (not necessarily terminate) warpd before locking the display,  he will be unable to access the machine unless he logs in remotely and kills either warpd or the locker.  It's very easy to forget to deactivate warpd before locking.

**Comment by OSS542** [comment]
To trigger this, I leave warpd active (ex. in normal mode) and lock the display via i3lock.  I will be locked out of the machine.

**Comment by rvaiya** [comment]
How do you run i3lock while warpd is active? As mentioned in the man page, warpd is incompatible with other programs which grab the keyboard, though I'm curious to know how you are triggering this bug.

**Comment by OSS542** [comment]
I should have considered this.  I use a voice response system to issue commands when away from the keyboard (and to show off to the wife...:-).  One of the voice commands is for locking the console, and runs from a script triggered by the voice response system.   That script calls i3lock.  That would explain how the lockout happened then.  I need to have the script terminate warpd prior to calling i3lock.

**Comment by OSS542** [comment]
This might be an issue for anyone else in a similar situation, but is not strictly speaking a warpd bug, so I'm closing this.  Thank youi very much for your very kind and prompt attention.
