### ISSUE TITLE
release 1.3.3 (not commit) fatal build errors, git assumed ?

### ISSUE THREAD

**Issue by OSS542** [rvaiya/warpd#195]
It appears that the Makefile assumes that a ".git" directory is present.  This is not the case with the release archive as opposed to a "commit" archive.
Note: fatal errors follow non-fatal:

fatal: not a git repository (or any of the parent directories): .git
...
rm: cannot remove 'src/config.o': No such file or directory
rm: cannot remove 'src/grid.o': No such file or directory
rm: cannot remove 'src/grid_drw.o': No such file or directory
rm: cannot remove 'src/hint.o': No such file or directory
rm: cannot remove 'src/histfile.o': No such file or directory
rm: cannot remove 'src/history.o': No such file or directory
rm: cannot remove 'src/input.o': No such file or directory
rm: cannot remove 'src/mouse.o': No such file or directory
rm: cannot remove 'src/normal.o': No such file or directory
rm: cannot remove 'src/screen.o': No such file or directory
rm: cannot remove 'src/scroll.o': No such file or directory
rm: cannot remove 'src/warpd.o': No such file or directory
rm: cannot remove 'src/platform/X/hint.o': No such file or directory
rm: cannot remove 'src/platform/X/input.o': No such file or directory
rm: cannot remove 'src/platform/X/mouse.o': No such file or directory
rm: cannot remove 'src/platform/X/screen.o': No such file or directory
rm: cannot remove 'src/platform/X/X.o': No such file or directory
make: [Makefile:61: clean] Error 1 (ignored)
...
cc -I /usr/include/freetype2 -L /usr/X11R6/lib   -c -o src/warpd.o src/warpd.c
src/warpd.c: In function ‘print_version’:
src/warpd.c:330:18: error: expected ‘)’ before ‘VERSION’
  330 |  printf("warpd v" VERSION " (built from: " COMMIT ")\n");
      |                  ^~~~~~~~
      |                  )
src/warpd.c: In function ‘main’:
src/warpd.c:434:28: error: expected ‘)’ before ‘VERSION’
  434 |   printf("Starting warpd v" VERSION " (" COMMIT ")\n");
      |                            ^~~~~~~~
      |                            )
make: *** [<builtin>: src/warpd.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by rvaiya** [comment]
This should be fixed in the latest commit.
