### ISSUE TITLE
build assumes /usr/share/man/man1 and /usr/bin are present

### ISSUE THREAD

**Issue by OSS542** [rvaiya/warpd#196]
The Makefile assumes that <prefix>/share/man/man1/ and <prefix>/bin/ are present.  If $DESTDIR is defined to use a different prefix (ex. a temporary build root), these must be created manually before running "make".  Most Makefiles handle this using "mkdir -p ..."

**Comment by rvaiya** [comment]
This should be fixed in the latest commit.
