### ISSUE TITLE
secondary keyboard input after warpd is launched not detected

### ISSUE THREAD

**Issue by Khqi** [rvaiya/warpd#199]
After warpd enter hint, grid or normal mode, only keyboard input from laptop's keyboard is detected. Keyboard input from secondary keyboard only passed to the background application. The launch keybind works as intended
![Screenshot_2022-10-28_00-35-46](https://user-images.githubusercontent.com/64934526/198348393-bad32149-8b9d-4385-afd4-ceca6fa3cc0a.png)

**Comment by rvaiya** [comment]
Are you plugging in the keyboard *after* starting one of warpd's modes?

**Comment by Khqi** [comment]
no. i hope this help 
![Screenshot_2022-10-28_21-18-03](https://user-images.githubusercontent.com/64934526/198604523-d2d1a600-101a-4f13-90e7-3fc29169b3d1.png)
