### ISSUE TITLE
Add the option to use the system cursor 

### ISSUE THREAD

**Issue by MiliAxe** [rvaiya/warpd#205]
It would be nice if there was an option to use system's cursor instead of the rectangle provided by warpd. 
Thanks for the great extension.

**Comment by MiliAxe** [comment]
_Update:_
I have created a [fork](https://github.com/MiliAxe/warpd) of this repository and added an option of `virtual_cursor` which is disabled by default and specifies whether a box gets rendered in normal mode. Maybe add this option in the main repository as well?

**Comment by rvaiya** [comment]
This should be available in the latest commit in the form of `use_system_cursor`.

**Comment by rvaiya** [comment]
Update: the option has been renamed `normal_system_cursor`.

**Comment by MiliAxe** [comment]
Great! Thanks for the update.
