### ISSUE TITLE
Option -l would freeze macOS when regranting privacy permission

### ISSUE THREAD

**Issue by BerginJay** [rvaiya/warpd#207]
When using the option `-l` in the command line, warpd would prompt "Waiting for accessibility permissions", but the permission had already been granted. Warpd would stop at this stage, and there would be no other output. When opening the privacy settings and trying to regrant permission (i.e., uncheck the check box of warpd and try to click it again), the system would stop responding to keyboard and the mouse can only move but not click. The check box is unchecked at this moment. Since the system stops responding to mouse clicks, there is nothing one can do but shut down the system.

**System**: macOS 12.6.1
**warpd version**: v1.3.5
**Installation**: build from source

**Comment by prolificprole** [comment]
Are you upgrading? Did you run `sudo tccutil reset Accessibility` first?

**Comment by BerginJay** [comment]
I'm not upgrading from an old version. After running this and regrant the permission, now using the option `-l` would cause segmentation fault. I had run `launchctl unload /Library/LaunchAgents/com.warpd.warpd.plist && launchctl load /Library/LaunchAgents/com.warpd.warpd.plist` and `launchctl kickstart -k gui/$UID/com.warpd.warpd`, and reboot.

**Comment by rvaiya** [comment]
Can you try the latest commit?

**Comment by BerginJay** [comment]
Bravo! I tried the latest commit, and it works perfectly now! Thanks!
