### ISSUE TITLE
Normad mode for call something

### ISSUE THREAD

**Issue by ajfpay** [rvaiya/warpd#208]
I use so many workspaces on X11 gnome, can custom on a normal mode like a key "i" for Alt+1(launch app or change workspace)?

**Comment by ajfpay** [comment]
this example, for call Alt+1

![image](https://user-images.githubusercontent.com/53251872/201558489-7e064d76-b865-45bd-ba81-7ebc80601814.png)

**Comment by rvaiya** [comment]
What you effectively want is a kind of passthrough mode. This is currently not possible and there are no plans to implement it. See #48.

**Comment by ajfpay** [comment]
> What you effectively want is a kind of passthrough mode. This is currently not possible and there are no plans to implement it. See #48.

I think must be set xdotool and combine some features with keyd.

Great app, thanks for making it
