### ISSUE TITLE
Crash: crashing Xorg when input device is disabled with xinput

### ISSUE THREAD

**Issue by matheusfillipe** [rvaiya/warpd#22]
I want to disable my laptop's built in keyboard and I used to do so with: `xinput disable 6` (or whatever is the device's id) . The problem is that when the keyboard is disabled if I try to use warpd (from my other usb connected keyboard) Xorg suddenly crashes.
Here is a bit of the syslog while the crash.
[syslog.txt](https://github.com/rvaiya/warpd/files/5215753/syslog.txt)

I was always able to reproduce this. (Arch Linux)

**Comment by rvaiya** [comment]
Thanks for reporting this. It seems this is the root cause of the crash triggered by a VT change. It should be fixed in the latest commit. In the future please always include the output of `warpd -v` so I can be sure you are running the latest commit,

**Comment by matheusfillipe** [comment]
Works on 08ed81af04c7b63b185e66385602d5795489a2c1 to me!
