### ISSUE TITLE
Feature: Consider xmodmap remaps

### ISSUE THREAD

**Issue by matheusfillipe** [rvaiya/warpd#23]
I use xmodmap to remap the Caps_Lock to Esc, which is a usual thing for vim users I guess. In hints mode it just ends when I hit my remapped Caps_Lock, but I guess that would happen for any other invalid key. In discrete mode it doesn't work though, even thought is remapped, I have to hit the original Esc key. Also if I try and use Caps_Lock as my exit key in ~/.warprc it doesn't work because it expects the key that was remapped to be Caps_Lock which is my Alt__Right. 

I guess that is because warpd is doing things on a different level but what I don't get is that warpd seems to detect the key that was remapped to Caps_Lock but not the one that was remapped to be Esc instead. I am leaving both the original Esc and Caps_Lock acting as Esc, could that be why?

**Comment by rvaiya** [comment]
warpd works by storing the keycode at start up so you should ensure that your remapping has been done before you start the daemon. Additionally having multiple keys mapped to the same keycode can interfere with the input logic (so you should remap the real escape key to be something else). It is not possible to support this without making non trivial changes to the input logic but given that it is relatively rare and likely will produce bugs in other apps it is probably advisable to just alter your keymap.

**Comment by rvaiya** [comment]
warpd works by storing the keycode at start up so you should ensure that your remapping has been done before you start the daemon. Additionally having multiple keycodes mapped to the same keysym can interfere with the input logic (so you should remap the real escape key to be something else). It is not possible to support multiple keycodes without making non trivial changes to the input logic but given that it is relatively rare and likely will produce bugs in other apps it is probably advisable to just alter your keymap. This is probably why Control_L and Control_R each have their own keysym.

**Comment by rvaiya** [comment]
To clarify something like

```
xmodmap -e 'keysym Escape ='
xmodmap -e 'keysym Caps_Lock = Escape'
xmodmap -e 'clear lock'
pkill warpd;warpd
```

should achieve what you want (starting from a fresh X config). It is important to run warpd last.

**Comment by matheusfillipe** [comment]
Oh I get it.. Sad. I like to left both acting as the Esc key. There are no workarounds right?

**Comment by rvaiya** [comment]
I thought of a way to implement support for overloaded keysyms without too much hassle. I can't think of any edge cases at the moment, but they may emerge. Try this latest commit.

**Comment by matheusfillipe** [comment]
Works with both Esc's! (Caps_Lock and the unchanged Esc!) Just as a wanted!!
