### ISSUE TITLE
Feature Request: Horizontal scroll

### ISSUE THREAD

**Issue by matheusfillipe** [rvaiya/warpd#24]
Would it be possible to add horizontal scroll? Some applications bind this to shift + scroll wheel, but mostly for notebooks there is touchpad action/gesture to horizontally scroll that works in most applications. Would it be possible to emulate that? 

Once again thanks a lot for this great project! I've been using it all the time.

**Comment by rvaiya** [comment]
Sure, I've been meaning to add that at some point. I will have a crack at
it tomorrow.

**Comment by rvaiya** [comment]
Sorry for the prolonged response. I had some work sitting on my branch that I had too clean up and push. I have added horizontal scroll and made a few other changes to the way warpd works. See the latest commit message for details. If you have any questions don't hesitate to contact me.
