### ISSUE TITLE
Many missing keys on OS X

### ISSUE THREAD

**Issue by wearpants** [rvaiya/warpd#240]
Most nonprinting keys are unavailable on OS X; also there is no distinguishing between keypad numbers and regular keyboard numbers. Probably related to PR #220

Guessing this is occurring from the filtering here: https://github.com/rvaiya/warpd/blob/6a0aae37c4b5e20c19b280b491f675b4c9ad9565/src/platform/macos/input.m#L405

Current list of keys: [warpd-osx-keys.txt](https://github.com/rvaiya/warpd/files/11473956/warpd-osx-keys.txt)
List of key codes ripped from `Events.h`: [osx-keycodes.txt](https://github.com/rvaiya/warpd/files/11474000/osx-keycodes.txt)

It would be nice to support the full OS X key set, and distinguish the keypad from the regular keyboard (I bought a standalone Bluetooth keypad just for the purposes of used with warpd)

**Comment by rvaiya** [comment]
Keypad codes should be supported in the latest commit. The OSX input handling logic is a bit of a mess (partly OSX's fault). warpd is currently in maintenance mode, pending deprecation by the integration of its more useful features into keyd.
