### ISSUE TITLE
"unbind" doesn't work on all options with keys.

### ISSUE THREAD

**Issue by alanxoc3** [rvaiya/warpd#245]
I'm running the latest version (with wayland):

```
warpd v1.3.5 (built from: 31192c3)
```

"unbind" does not work in this specific case:

```
> echo 'oneshot_buttons: unbind unbind unbind' > f.txt; warpd -c f.txt -f --oneshot
ERROR: unbind is not a valid key name
wayland: mouse hiding not implemented
```

It does work for me for every other option I've noticed.

**Comment by rvaiya** [comment]
You need `oneshot_buttons: unbind`. You can't unbind a single key in a button group.

**Comment by alanxoc3** [comment]
Ok, that works. I can close this one.
