### ISSUE TITLE
Commandline option to clear all keybindings.

### ISSUE THREAD

**Issue by alanxoc3** [rvaiya/warpd#247]
When setting a new keybinding in the config file, the previous keybindings still work. Example:

```
echo -e 'grid_up: K\ngrid_left: H\ngrid_down: J\ngrid_right: L' > /tmp/f.txt; warpd -c /tmp/f.txt -f --grid
```

Both "wasd" and "JKHL" will move the grid around. This will disable "wasd":

```
echo -e 'grid_up: unbind\ngrid_left: unbind\ngrid_down: unbind\ngrid_right: unbind\ngrid_up: K\ngrid_left: H\ngrid_down: J\ngrid_right: L' > /tmp/f.txt; warpd -c /tmp/f.txt -f --grid
```

But specifying unbind for everything is annoying. Some ideas to resolve this:
- warpd defaults to not setting any keybindings and has a default config file with all the defaults. When the "-c" option is used, the default config file is ignored.
- add a cli option that sets all keybindings to "unbind".
- the "-c" option unbinds all keys.

**Comment by rvaiya** [comment]
This is by design. There are a number of problems with warpd's input system which exist for historical reasons. Current efforts are being devoted towards merging the project with keyd and deprecating the current code base.
