### ISSUE TITLE
Set Caps Lock remaped to Escape as exit key

### ISSUE THREAD

**Issue by gmnz** [rvaiya/warpd#249]
Hi,

I use this command "setxkbmap -option caps:escape" to remap my Caps Lock to Escape. How can I set "exit" and "hint_exit" in warpd config to this remaped key, please?

**Comment by eirikb** [comment]
Same issue here. Shouldn't this be transparent for warpd?

**Comment by konvits** [comment]
try `caps:swapescape` instead of `caps:escape`. worked for me.

**Comment by eirikb** [comment]
> try `caps:swapescape` instead of `caps:escape`. worked for me.

That worked! Awesome. Thanks :heart:
