### ISSUE TITLE
Be able to trigger shortcuts again wihout having to press the full key combination again

### ISSUE THREAD

**Issue by matheusfillipe** [rvaiya/warpd#28]
Here I am to annoy you again :P Before 65e8cd6e7d91e45547bc9d6838d4794753e59ba3 if I am right it was possible to trigger the shortcuts fro scrolling just by releasing and pressing only one of the keys of the key combination. I am not sure if this affects the scroll only but is the one that most annoys me. 

Let me explain better. Let's say I have `scroll_down_key: A-a` on my warprc. Then i launch warpd and scroll on a long page with Alt + a, but then I release the a key only, the page stops scrolling as expected, but then If i press a again (and I was holding alt all this time) the page won't scroll even though I am pressing alt+A. I will have to release and press Alt and a for the key combination to work again.  

In another words: Hold Alt, hold A for a while, then release A only. The scroll stops as expected, but then holding A again doesn't trigger the scroll anymore. 

I know that for those cases I could be just using normal mode and scrolling with a single key. I just got used with the shortcut way though :P.

**Comment by rvaiya** [comment]
No need to apologize this is what the issue tracker is for :P. This was indeed a regression. I don't use the feature enough to have noticed so I thank you for pointing it out. It should be fixed in the latest commit. I have also added vim style history via C-o and C-i.

**Comment by matheusfillipe** [comment]
What?? Vim history? :heart_eyes:...... GREAT! I just tested it

The shortcuts are fixed!

Your project is just getting quite a lot.... i don't even know how to say :P but cool! 

Consider hints for the history mode, like by default only use character keys for the hints of the last 16 positions in history. (Maybe when triggering it from hints mode?).
