### ISSUE TITLE
Change to Hints mode within Normal mode.

### ISSUE THREAD

**Issue by matheusfillipe** [rvaiya/warpd#29]
Is it possible to change directly to hints mode within normal mode? I kinda miss the hints mode after pressing v for selecting/dragging in hints mode. Would be kinda nice to be able to switch from normal to hints with the shortcut directly. 

Right now it is possible to change from hints mode to normal with the assigned keybinding for normal but the contrary is not possible. 

Thanks a lot for the great project! Keep up the good work!

**Comment by rvaiya** [comment]
Yes, this is in fact the new intended usage. You should treat normal mode
as the default mode from which it is possible to access hint and grid mode
for long range movement. The default keybinding for this is 'x' but you can
can configure it with 'normal_hint_key'.

**Comment by rvaiya** [comment]
To clarify `normal_hint_key` and `normal_grid_key` are used to activate
hint and grid mode from normal mode. `grid_activation_key` and
`hint_activation_key` are additional activation keys which jump directly
into those modes and are functionally equivalent to using
`normal_activation_key` and then `normal_(grid|hint)_key`. My
recommendation is to bind `normal_activation_key` to a single key on your
keyboard and then to use the normal mode keys to access the other modes
(like you might enter insert mode in vim). This makes any mode accessible
within two keys without requiring multiple activation keys.

**Comment by matheusfillipe** [comment]
Hmm what you are saying there should that already work? pressing 'x' in normal mode do nothing for me, not even logs with `warpd -f`.

**Comment by matheusfillipe** [comment]
oh setting:
```
normal_hint_key: M-x
```

Which is the same as my hint_activation_key made it work.
