### ISSUE TITLE
Rounded corners for hints mode

### ISSUE THREAD

**Issue by matheusfillipe** [rvaiya/warpd#31]
Don't ask me why this feature but I think it would look nice. I fooled around with it a bit (first time ever using X11 libs so might be the shittiest way) and came up with this relevant part of the code:

src/hint_drw.c
```c
void drawRoundEdgedRectangle(Pixmap *shape_mask, GC *shapeGC, unsigned int x, unsigned int y, unsigned int w, unsigned int h, unsigned int r)
{
	XFillArc(dpy, *shape_mask, *shapeGC, x,y, 2*r,2*r, 64*90*1,64*90);
	XFillArc(dpy, *shape_mask, *shapeGC, x+w-2*r,y, 2*r,2*r, 64*90*0,64*90);
	XFillArc(dpy, *shape_mask, *shapeGC, x+w-2*r,y+h-2*r, 2*r,2*r, 64*90*3,64*90);
	XFillArc(dpy, *shape_mask, *shapeGC, x,y+h-2*r, 2*r,2*r, 64*90*2,64*90);

	XFillRectangle(dpy, *shape_mask, *shapeGC, x+r,y, w-2*r, h);
	XFillRectangle(dpy, *shape_mask, *shapeGC, x,y+r, w, h-2*r);
}

void hint_drw_filter(size_t *indices, size_t nindices)
{
	if(!nindices) {
		XUnmapWindow(dpy, win);
		return;
	}

	size_t i, n = 0;
	static XRectangle recs[MAX_HINTS];
	GC shapeGC ;
	XGCValues	xgcv;
	Pixmap shape_mask;
	XWindowAttributes info;
	XGetWindowAttributes(dpy, DefaultRootWindow(dpy), &info);
	shape_mask = XCreatePixmap (dpy, win,
				    info.width, info.height, 1);
	shapeGC = XCreateGC (dpy, shape_mask, 0, &xgcv);
	XSetForeground (dpy, shapeGC, 0);
	XSetForeground (dpy, shapeGC, 1);

	unsigned int fallback_border_radius = 10;
	for (i = 0; i < nindices; i++) {
		struct hint *h = &hints[indices[i]];
		if (border_radius == 0){
			// This is still much faster
			recs[n].x = h->x;
			recs[n].y = h->y;
			recs[n].width = h->w;
			recs[n++].height = h->h;
		}
		else if (h->w < border_radius || h->h < border_radius )
			drawRoundEdgedRectangle(&shape_mask, &shapeGC, h->x, h->y, h->w, h->h, fallback_border_radius);
		else
			drawRoundEdgedRectangle(&shape_mask, &shapeGC, h->x, h->y, h->w, h->h, border_radius);
	}

	if (border_radius == 0){
		XShapeCombineRectangles(dpy, win,
					ShapeBounding,
					0,0,
					recs, n,
					ShapeSet,
					Unsorted);
	}
	else {
		XShapeCombineMask (dpy, win, 
					 ShapeBounding, 0,0, shape_mask, ShapeSet);
		XShapeCombineMask (dpy, win, 
					 ShapeClip, 0,0, shape_mask, ShapeSet);
	}
	XFreePixmap (dpy, shape_mask);

	XMapRaised(dpy, win);
	XCopyArea(dpy, backing_pixmap, win, gc, 0, 0, winw, winh, 0, 0);
	XFlush(dpy);
}

```

And it looks like this:
![image](https://user-images.githubusercontent.com/24435787/124053019-d513ed80-d9f5-11eb-8212-71d2e821be2c.png)

The way I have it now makes border_radius a global in hint_drw.c and I already have it on the .warprc as hint_border_radius. However it increased the lag to load hints mode, not enough to bother me on my machine though, but I think is too many draw calls.

I now this is a minor thing but the future has rounded edges! I know this is a very useless feature If you want to kill <s>some time</s> consider this I could submit a PR or maybe you have a totally better and different idea for this.

**Comment by rvaiya** [comment]
Sorry for the prolonged response. I've been meaning to look at this for a while. This is a good first approximation however the problem, as you have observed, is that it involves a massive performance penalty. Masking out arbitrary pixmaps using XShapeCombineMask as you do here seems to be expensive.  I'm not sure if this is a problem with Xlib (which may be generating too many requests) or (more likely) the with the implementation of the shape extension itself. If it is the latter (as I suspect) it is unlikely anything can be done.

Having said that, if you are able to make it performant I would be happy to take another look at it. As you've probably discovered there isn't much good X documentation floating around so you will likely have to piece it together by studying ancient reference documentation and scouring the internet for source.

The original code had a similar problem before I discovered I could abuse the shape extension to achieve my objective. The input system is also a giant kludge. X wasn't really designed for this sort of thing, so getting warpd to its present level of usability required a fair bit of creativity.

**Comment by matheusfillipe** [comment]
Yeah I think you are right that the bottleneck is drawing all those shapes. I don't think or know if it is possible to make this more efficient at all and is probably not worth to invest time on this anyway. 

Anyway did you give it a try: https://github.com/matheusfillipe/warpd/tree/rounded-corners ? . On my machine it adds about 100 ms to the hints load and this is fine for me. Anyway it is implemented in a way that it will fall back to the old and faster way if `hint_border_radius` is set to 0 so it is something optional that users can try and give up if it is a major performance.

**Comment by rvaiya** [comment]
I did try it, unfortunately it was unusable on my machine. 100 ms is a long time in the context of UX so I would prefer to make it performant before considering it for inclusion.

**Comment by rvaiya** [comment]
I spent some time trying to optimize this and was able to achieve something usable. It looks like the main bottleneck was in attempting to map a shape masked window. It appears as though X doesn't cache the masking operation, the main solution was to move the window offscreen when not in use in conjunction with a few other rendering tweaks. It's a big ugly but seems to work well enough. Let me know if you discover any new bugs. I have credited you in the commit message and added a list of contributors to the README. Thanks for your efforts.

**Comment by matheusfillipe** [comment]
Oh you didn't have to worry about all that crediting  :P 
Well performance is excellent now, I can't see any difference between with and without rounded corners now!
Oh I see, so the window is always loaded now. This might be actually an overall optimization then! 
I think it is ok to close this. Thanks for your time on this!

**Comment by rvaiya** [comment]
No problem. Thanks for putting some work into it. The round corners are unwittingly starting to grow on me :).
