### ISSUE TITLE
Distinct button keys for "oneshot" and "stay active" clicks

### ISSUE THREAD

**Issue by wearpants** [rvaiya/warpd#38]
Following from 7564ecea6718a316e3a955f81f212cc2c326765f, it'd be nice to have different buttons for "oneshot" and "stay active" modes - when _entering_ a warpd mode, I sometimes don't know if I'm going to want oneshot or active mode ahead of time, and only decide when I _press_ the button (or maybe I'll want  a series of clicks, and then want to click-and-exit on the last one). Separate keysyms for these two behaviors would be really nice.

**Comment by rvaiya** [comment]
> when entering a warpd mode

By which I assume you mean when entering another mode from normal mode (e.g `g`) since the activation keys already do this. I agree that this make sense and will release a patch shortly.

**Comment by rvaiya** [comment]
The latest commit adds `normal_oneshot` (default `n`).

**Comment by rvaiya** [comment]
In retrospect having dedicated oneshot activation keys makes less sense than having a dedicated oneshot click key which works in any mode. I've removed the activation keys in cb22e92 for simplicity.

**Comment by wearpants** [comment]
this works great!!! The ability to use both modes (oneshot & continuous) it's super helpful, can do some really sophisticated sequences quite easily now.

Can we get similar functionality for buttons 2 and 3? I'll often use right click to bring up a menu and then use the arrows to navigate  / use middle click to paste and then type.

**Comment by wearpants** [comment]
oh other major oneshot button 2 use case is opening background tabs in browser

**Comment by rvaiya** [comment]
`normal_oneshot` has been replaced with `oneshot_buttons` in the latest commit.
