### ISSUE TITLE
unindented scroll [Question]

### ISSUE THREAD

**Issue by Ultrahalf** [rvaiya/warpd#39]
In a scrollable page pressing `H`/`L` (high/low) triggers scroll in select mode(`v`)
Is this intended or a bug? I was expecting to select till the top of the screen like how it works in normal mode but it looks like it scrolls to the top of the page

config
```
normal_size: 10
normal_beginning: S-i
normal_end: S-a
scroll_down_key: A-n
scroll_up_key: A-e
scroll_right_key: A-i
scroll_left_key: A-m
movement_increment: 10
```

**Comment by Ultrahalf** [comment]
if thats intensional it would be nice if they were like `gg` `G` in select mode

**Comment by Ultrahalf** [comment]
> consequently drag + hint mode can be a superior method for surgically selecting text (though it may at first be less intuitive).
should have seen this smh

**Comment by rvaiya** [comment]
By 'select' mode I assume you mean when performing a drag operation (v by
default). The drag operation shouldn't change any of the mode key bindings.
If you are in normal mode H and L should still move the cursor to the top
and bottom of the screen respectively and seem to behave consistently on my
machine.

Are you saying that the following triggers a scroll?

```
A-M-c
v
H
```

If so, I can't seem to reproduce this. What commit have you built from?
(warpd -v)

**Comment by rvaiya** [comment]
Actually I suppose `M-A-c` `v` `L` does make a window scroll if you are highlighting text, but this is because it has the same effect of dragging a real mouse to the bottom of the window. If this is the case it should continue until you stop dragging by pressing `v` again (much like releasing a real mouse cursor). Perhaps this is what you are describing.

**Comment by Ultrahalf** [comment]
> Actually I suppose `M-A-c` `v` `L` does make a window scroll if you are highlighting text, but this is because it has the same effect of dragging a real mouse to the bottom of the window. If this is the case it should continue until you stop dragging by pressing `v` again or move the mouse cursor slightly above the bottom of the window (much like releasing a real mouse cursor). Perhaps this is what you are describing.

yes thats what i was describing
I didn't know that I could stop the drag mode by pressing v again

```
Built from commit: bc5de097ae3e1de944c04e18c4a9244f585096c5
Compiled from git commit: bc5de097ae3e1de944c04e18c4a9244f585096c5
```

how can the config be moved to `~/.config/.warprc`

**Comment by Ultrahalf** [comment]
man.md
```
> buttons: Keys corresponding to mouse buttons (4/5 == scroll down/scroll up while 6/7 correpond to scroll left/right). (default: m,comma,period,q,e,r,t).
```
i think default buttons are m,comma,period, ~`q,e,r,t`~  y,u,i,o?

strangely I found all problems with scroll are mostly because of bindings(colemak). and kmonad? I get the double tap effect i.e `A-n / A-e` in my binding or default `u/i` but not the normal scroll i.e pressing and holding `u/i` maybe because of the homerow mods it pretends to be shift/ctrl when i hold that down

**Comment by Ultrahalf** [comment]
```
buttons: comma,period,slash,f,u,q,p
scroll_down_key: A-f
scroll_up_key: A-u
scroll_right_key: A-p
scroll_left_key: A-q
``` 
fixed my issue 
it was because of homerow mods i switched the keys
thanks for your time.

**Comment by rvaiya** [comment]
> i think default buttons are m,comma,period, q,e,r,t y,u,i,o?

These were modified at some point. You should make sure you are running the latest commit to avoid issues. You may have to make some configuration changes if you were used to the old defaults.

> it was because of homerow mods i switched the keys

Thanks for closing the loop on this.

> I didn't know that I could stop the drag mode by pressing v again

`v` just toggles left mouse down. It is the equivalent of holding a mouse button. It would be trivial to automatically release the button when the user moves the cursor to the top or bottom of the screen in drag mode but that would have other unintuive consequences when you aren't selecting text (suppose you are dragging a file), so I am inclined to keep the default behaviour.

**Comment by Ultrahalf** [comment]
> v just toggles left mouse down, it is the equivalent of holding a mouse button. It would be trivial to automatically release the button when the user moves the cursor to the top or bottom of the screen in drag mode but that would have other unintuive consequences when you aren't selecting text (suppose you are dragging a file), so I am inclined to keep the default behaviour.

that makes sense
