### ISSUE TITLE
The Config Options section under man.md is broken

### ISSUE THREAD

**Issue by B1T3X** [rvaiya/warpd#44]
The Config Options section in the man.md file is broken since the last commit. No config options are listed and all that's shown is:
```
:
{opts}
```

**Comment by rvaiya** [comment]
Are you referring to 4209127ff? The man page shipped in that commit seems to have an intact options section.

**Comment by rvaiya** [comment]
Ah, sorry I assumed you were referring to the man page (warpd.1.gz). man.md is no longer an intermediate stage of man.md.t. The file was never intended to be read directly, but used as input to generate the man page programatically. You can find a list of options in `man warpd`.

**Comment by rvaiya** [comment]
I'm closing this for now.

**Comment by rvaiya** [comment]
update: Options should now be visible in the markdown version.
