### ISSUE TITLE
alternative keymap support?

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#45]
Hi, 

since my recently found keymap nirvana through keyd, I naturally looked through your projects and started using warpd as well, thanks again for making both programs! Since I'm using Dvorak, I had to alter the source code by hand so that the hint chars actually match this layout (which is of course a very ugly solution). It would be much nicer to make warpd agnostic of the currently active X keymap, in the sense that the hint-chars drawn on screen are matched with the X keysyms associated to the keys. If that would require substantial coding, how about introducing a simple translation table between drawn hint-chars and actual keys (which one would have to edit by hand)?

**Comment by rvaiya** [comment]
I've been avoiding publicizing this project too much since it still has some warts, but it is nice to see people are still discovering it independently :P. 

 > It would be much nicer to make warpd agnostic of the currently active X keymap,

It shouldn't be too hard to do this for the English alphabet (I believe the original implementation did this), but adding proper multi language support (and making it cross platform) would involve some additional effort. It's worth noting that if you do all your remapping in keyd and keep a qwerty X map you can avoid this problem ;).

**Comment by rvaiya** [comment]
I've gone ahead and pushed a patch which should solve this for English layouts.

**Comment by herrsimon** [comment]
Thanks for the quick reply. You're absolutely right that all remapping should be done in keyd. In my case, the reason why I'm keeping a separate dvorak keymap (also in /etc/vconsole.conf)  is that I have to enter a rather long unlock-password when booting up (which I would like to do in dvorak) and don't want to fiddle with a custom initrd. As I also do my regular login via vconsole, while keyd is already running, I chose the path of least resistance and kept dvorak outside of keyd. However, I will take your answer as motivation to get dvorak into the initrd and then move all dvorak remapping from vconsole.conf and X into keyd.

I'm closing this issue for now, thanks again and have a nice weekend!

**Comment by herrsimon** [comment]
Oh, just saw your patch after my last comment, thanks so much!

**Comment by rvaiya** [comment]
> I have to enter a rather long unlock-password when booting up (which I would like to do in dvorak) and don't want to fiddle with a custom initrd. 

Ah, that makes sense :P. cryptsetup and the like can indeed be nuisance.

> Oh, just saw your patch after my last comment, thanks so much!

I haven´t extensively tested it, so let me know how it goes. Feel free to reopen this if you encounter any issues.

**Comment by herrsimon** [comment]
I have just used it for a couple of hours and it works like a charm. Will still switch to doing all dvorak mapping in keyd now, getting dvorak into the initrd is actually rather simple (trivial modification of the stock 'keymap' hook), and it gets rid of nonstandard xorg.conf and vconsole.conf files. 

Another question, not directly related: when keyd creates its virtual input device, the options in xorg.conf are not honored (i.e. the device has neither dvorak layout, nor the 'compose:menu' option, so I have to issue 'setxkbmap' explicitly after starting keyd). Is there something keyd could do (emit some event?) to make X aware that a new keyboard has been added and the options should be applied to it? This is of course not a big issue at all.

**Comment by rvaiya** [comment]
> the options in xorg.conf are not honored (i.e. the device has neither dvorak layout, nor the 'compose:menu' option

What does your xorg.conf look like? The virtual device should appear as a normal keyboard bound by the described X rules. If you use setxkbmap and restart the daemon, you will lose any changes, since this is the equivalent of unplugging and re-plugging the device, but your xorg.conf rules should still be honoured.

**Comment by herrsimon** [comment]
Sorry, completely forgot to reply to this: My xorg.conf used to look like

```
Section "InputClass"
    Identifier "keyboard defaults"
    MatchIsKeyboard "on"
    Option "XkbLayout" "dvorak"
    Option "XKbVariant" "dvorak"
    Option "XKbOptions" "compose:menu"
EndSection
```

and it was actually not in `xorg.conf` but in the `/etc/X11/xorg.conf.d` directory. After moving dvorak remapping into keyd and changing the above to us-layout, the `compose:menu` option is still not applied after starting (or restarting) keyd, and the same is true the newly added ` keypad:pointerkeys` option. However, I ended up removing the file altogether and activating these two options in a keyd launcher script.

**Comment by rvaiya** [comment]
Odd, I can't seem to reproduce this. Restarting keyd whilst X is active seems to have no effect on my xorg config options (setxkbmap excepted, but this is expected).
