### ISSUE TITLE
Oneshot hint mode, no normal mode activation

### ISSUE THREAD

**Issue by kuapi0** [rvaiya/warpd#47]
I'm loving the hint mode for fast warps, but it auto-switches to normal mode every time forcing me to press escape.
Thought something like a `hint_oneshot_activation_key` would be useful for other trackpoint users like me.

**Comment by rvaiya** [comment]
What would be the use case? Normally the user wants to warp, make some adjustments and click something. I can't think of a reason that you would want to warpd to a location and immediately exit.

**Comment by kuapi0** [comment]
I can only speak for myself, but I'm just too comfortable with my trackpoint, so I use it for fine adjustments instead of normal mode.

**Comment by herrsimon** [comment]
I also use trackpoint keyboards most of the time and second this request for exactly the same reason.

**Comment by rvaiya** [comment]
Alright, I'll add this later when I have some time.

**Comment by kuapi0** [comment]
Thanks

**Comment by rvaiya** [comment]
This has been added to the latest commit. The default binding is `A-M-l`.
