### ISSUE TITLE
passthrough of unbound key events

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#48]
It would be nice if warpd would passthrough (on a press/release level) unbound key events while active, unless this creates unwanted side effects I didn't consider. The icing on the cake would be to keep modifier state when activated, so that for example an activation via C-j would only send the release events for j and control when these keys are physically released. In this case, warpd should of course be aware that control is currently held so that bindings work as expected.

My use case is as follows: At work I'm regularly forced to use gui applications and then switch between two gui windows to copy/paste text, select some ui element etc. The window switching is done via a key combination, as is magnification, and I also interact with the application via keyboard shortcuts.
I frequently also use a trackpoint, so that pointer movement is actually a mixture of warpd and physical trackpoint usage. The explicit activation/deactivation of warpd is quite cumbersome here.

To be even more explicit: I regularly have to copy parts of text from separate ui text fields into respective text fields in another ui window and then press a function key. Here I started switching from pure trackpoint usage to a combination of hint and drag mode, which is actually more efficient. What slows me down substantially is the explicit activation/deactivation of warpd in order to switch to the other window (they are too large to be shown side to side), paste, press the F-key and switch again. Oh, of course we don't have to argue about the bad design of the gui application in question and the horrible workflow it creates. I already tried to do so many times in vain...

**Comment by rvaiya** [comment]
Doing this in a cross platform way would be a little cumbersome. warpd was designed
with modality in mind, with the idea that the reduced cost of post-activation actions
(no need to use modifiers) would offset the cost of the initial activation.

The problems you describe might better be remedied by pairing warpd with some
keyd macros. For example, you could have a macro which exits keyd, pastes
the desired content, sends the function key, and reactivates warpd.

E.G

`macro(esc S-insert f12 A-M-c)`

Given that keyd hints are entirely deterministic, you could even bake window selection
into the macro (assuming invariant window positions).

Another thing you might want to try is overloading one of your modifier keys to function
as a warpd toggle.

E.G 
	meta = overload(meta, A-M-x)


This way mouse movement is always single keystroke away.

**Comment by herrsimon** [comment]
As always, thanks a lot for the detailed and helpful answer. What you are describing is very efficient and I will implement it in a special keyd-configuration which I will only be loaded when having to deal with the mentioned gui applications.

**Comment by nrabulinski** [comment]
Hey, I wanted to open a new issue but I found this one which sounds similar enough to what I want to achieve (Maybe you could point me in a better direction?)

I'd like to eventually replace all my mouse usage with this program but one thing that's still holding me back is the fact that not all modifiers are passed through and there are times when I want to drag my mouse with a modifier like ctrl or shift or meta.
For example, I cannot do block selection in my terminal screen by dragging my mouse with ctrl or move my windows by holding the meta key.

**Comment by rvaiya** [comment]
If support for this is added it will probably be confined to modifiers (@nrabulinski's use case). Work will need to be done for each platform. Given the renewed interest in the project I might invest some time in it later. keyd mouse support is currently on the backburner, but should eventually address a lot of warpd's current limitations.
