### ISSUE TITLE
capslock as modifier?

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#49]
Is it possible to use capslock as a modifier-key in key-combinations?

Currently I use keyd to do the very common and widespread capslock to meta mapping but as warpd seems to work on evdev level as well, bindings with a meta prefix (such as M-f) do not work in warpd unless the physical meta key is used. Unless I'm doing something wrong, would it be possible to add support in warpd for using capslock as another modifier key, for example by treating it as a regular shift key?

Use case: I would like to use keys on the homerow for clicking and add meta for oneshot clicks.

**Comment by rvaiya** [comment]
>  bindings with a meta prefix (such as M-f) do not work in warpd unless the physical meta key is used

warpd uses Xinput, so it should respect your keyd bindings. If you've done any remapping in X it might ignore that, but if you do something like `capslock = meta` in keyd, it should process `meta` as expected.

**Comment by herrsimon** [comment]
You are of course absolutely right, I did not mention the important details that the very key combination (M-f) I was expecting warpd to produce a oneshot mouse click was already bound in keyd to produce a mouse click. So warpd was just seeing mouse clicks and of course did not do anything.

Please excuse my false allegations, the problem was sitting in front of the screen!

**Comment by mechkit** [comment]
As a long time Linux user, command line lover, and programmer, I have always struggled to get any xinput config to stick. Recently I have used [sezanzeb/input-remapper](https://github.com/sezanzeb/input-remapper/) to remap keys at a level that warpd recognized. I have caps-lock mapped to escape (vim user), and right-alt as alt+meta. Input-remapper It is set up per-device, so lower level than xinput? Sorry, I am web developer, so you can't expect much from me.

**Comment by mechkit** [comment]
keyd looks good; I do like config files over UI.  I will give it a try. I would love to mimic what QMK can do, with any cheap keyboard/laptop.
