### ISSUE TITLE
Feature request: outline color for normal & grid mode

### ISSUE THREAD

**Issue by wearpants** [rvaiya/warpd#51]
I use an e-ink grayscale monitor, and it's sometimes hard to visually see the Square or grid depending on the color of whatever is on the screen. For example, #FF000 often appears the same as black (the monitor's rendering algorithm is somewhat adaptive but not amazing).

It'd be nice to be able to specify an outline color and size that gets drawn as a border to the  Square or grid lines (similar to the white border on the Black OS X native cursor)

**Comment by rvaiya** [comment]
Can't you just set `grid_color` to something which stands out on your screen?

**Comment by wearpants** [comment]
Setting cursor_color or grid_color alone won't do it because *everything is mapped to grayscale* and I can't control the underlying colors on web pages or in apps…

**Comment by rvaiya** [comment]
I see. I will add this to the todo list.

**Comment by rvaiya** [comment]
I've added this to the latest release.
