### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [rvaiya/warpd#53]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by rvaiya** [comment]
Thanks for reporting this. It is already licensed under the MIT license, which can be found at the top of most of the source files. I've just added a LICENSE file to the repository.
