### ISSUE TITLE
Installed it and executed it, but it got stuck?

### ISSUE THREAD

**Issue by cohen990** [rvaiya/warpd#58]
Hey I'm running arch linux with i3wm and wanted to give this a go

I hit A-M-x and jumped to the middle of the screen. All good so far

then I moved my mouse a little with the h-j-k-l keys. This worked fin

Then I moved the mouse with my actual mouse and it also moved

Then I started trying to type something in the terminal but all my keyboard input was being captured by the mouse process

I tried hitting A-M-x and A-M-c and A-M-g just randomly to see if any of them would help but none of them did anything

I eventually unplugged my keyboard and plugged it back in again. That gave me access to my keyboard again.

I checked the log file but the only line is the `Starting warpd` line.

Now I have full keyboard access but none of the warpd hotkeys are doing anything and my pointer is stuck as a little green square.

I tried to look for warpd with `systemctl list-units | grep warpd` but couldn't see anything. Was hoping to restart the service.

**Comment by rvaiya** [comment]
warpd is modal. You need to explicitly exit it when you are finished (`escape` by default) or use one of the oneshot keys (e.g `n`). If you unplug your keyboard while it is running it can wreak havoc because of some bugs in the input logic. If you are stuck you can ssh into the machine or switch to a virtual terminal and issue `pkill warpd`.

**Comment by cohen990** [comment]
maybe add something into the readme to explain how to get out of the broken state? Cos it was quite easy to find myself stuck. I can open a PR?

For what it's worth, I think I did try to hit escape, but I used my rebound caps lock which I guess is why it didn't work

**Comment by hab25** [comment]
> warpd is modal. You need to explicitly exit it when you are finished (escape by default) or use one of the oneshot keys (e.g n). If you unplug your keyboard while it is running it can wreak havoc because of some bugs in the input logic.

@rvaiya could this be solved in Linux by using a [udev RUN rule](https://man7.org/linux/man-pages/man7/udev.7.html#:~:text=inefficient%20event%20handling.-,RUN%7Btype%7D,-Specify%20a%20program) to exit the warpd mode and then restart warpd ?

Could the same or a similar mechanism could be used to help with this multiscreen hotplugging limitation?https://github.com/rvaiya/warpd/blob/a33c40031b8b54394f49f1e1cb17a18a0d8de02a/warpd.1.md?plain=1#L303

One problem you might have with this is that warpd doesn't prescribe a service management system (e.g. systemd) , and based on https://github.com/rvaiya/warpd/issues/113, I'm guessing you may not be interested in maintaining such things. 

If that's the case, what about opening up the [wiki section](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis) so the community can document this solution (as well as a systemd service file) there? I would guess that most warpd users can and would be open to using udev and systemd and would appreciate this solution being more easily implemented. You can put something like "warpd's maintainer does not maintain this wiki" at the top of the wiki and next to a link to the wiki in README.md .
