### ISSUE TITLE
Make Hint Mode buttons transparent so it doesn't block the view.

### ISSUE THREAD

**Issue by tildethine** [rvaiya/warpd#59]
The hint mode is amazing I don't have to use my mouse anymore but sometimes I can't see what's behind because the buttons indicator blocks it. Perhaps setting an opacity to make it transparent would solve this

**Comment by rvaiya** [comment]
The various color options are actually rgba options, so the last two hex digits correspond to opacity. Thus `#ff000011` will set the opacity to 6%. In order for this to work you will need a compositor (e.g compton). I should probably document this better.

**Comment by tildethine** [comment]
@rvaiya Can you link the manpage here btw? I can't find it in the github.

**Comment by rvaiya** [comment]
If you've installed warpd you can access the man page by typing `man warpd` into your terminal. If you want to become a man's man then you should type `man man`. In the meantime to you can man up [here](https://github.com/rvaiya/warpd/blob/master/man.md).

**Comment by rvaiya** [comment]
> Where should I edit this?

You probably want to modify `hint_bgcolor` in `~/.config/warpd/config`. You don't need to modify anything in compton, just ensure it is running (assuming you are not already running another compositor).

**Comment by tildethine** [comment]
It worked, thanks. I love this thank you for making this I don't need my mouse anymore lol.
