### ISSUE TITLE
Hint mod "crashes" on MacOS

### ISSUE THREAD

**Issue by dsych** [rvaiya/warpd#65]
> First of all, thanks *A LOT* for warpd! I just recently discovered it and my life changed forever.

Anyway, I have this weird bug on MacOS where Hint mode just gets stuck displaying hints and the only way to fix it is restarting warpd from console.

Here are the steps to reproduce it:
1. Active the `Normal` mode
2. Jump to the left side of the screen with the shortcut. note that i have the task bar on the left, so it shows up at this point.
3. Activate Hint mode(and jump anywhere)
4. Wait for ~30s in normal mode
5. Jump to the left side of the screen with a shortcut again
6. Open the Hint mode <- a this point warpd becomes unresponsive and i need to `pkill` it

The logs under `~/.config/warpd/warpd.log` contain the following:
```
Starting warpd: 1.0.2-beta
2022-03-30 18:02:08.150 warpd[95479:8124028] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection invalid
```

Moreover, I sometimes get this bug without the steps above. i think the only common theme here would be that i leave Normal mode running for a while and then trigger Hint mode.

**Comment by rvaiya** [comment]
Thanks for the detailed reproduction steps. It looks like macos times out the event listener after a certain period of time. This should be fixed in the latest commit.

**Comment by dsych** [comment]
works like a charm now, thanks!
