### ISSUE TITLE
Switching to different resolution monitor results in funky rendering

### ISSUE THREAD

**Issue by snowe2010** [rvaiya/warpd#67]
This is not a multimonitor request (though I would like that).

I started warpd on my laptop, with no external monitor plugged in. I plugged in a monitor, closed the laptop lid (still single monitor) and when I run warpd, it results in this funky rendering (had to take a photo with my phone, because there's no way to take a screenshot while the app is running).
![IMG_0432](https://user-images.githubusercontent.com/1534535/160957148-e3e85197-a029-4437-bbc8-80819b582989.jpg)

Note, this also happens with hammerspoon's grid api, so I'm guessing there's some common issue here.

**Comment by rvaiya** [comment]
Unfortunately multi-screen setups are completely unsupported at the moment. This is probably a function of preredering hints on a single screen. I intend to introduce multiscreen support shortly due to popular demand, though it will require some work on both platforms.

**Comment by rvaiya** [comment]
I'm closing this for now in favour of #62.
