### ISSUE TITLE
warpd -l shows no output

### ISSUE THREAD

**Issue by maxigaz** [rvaiya/warpd#68]
According to the man page, running `warpd -l` prints out a list of valid keys for its configuration file. However, no output appears when I run that command.

This happens both with and without warpd running as a daemon.

I'm using warpd installed from the AUR under Arch Linux.

PS: Thank you for this great tool!

**Comment by rvaiya** [comment]
Oops. Looks like I forgot to reimplement this after the 1.0 release. Thanks for drawing my attention to it. It should be fixed in the latest commit.

**Comment by maxigaz** [comment]
I can confirm that it works now. Thank you!
