### ISSUE TITLE
Feature request: custom background color for hint mode

### ISSUE THREAD

**Issue by akazukin5151** [rvaiya/warpd#72]
It would be nice if the background color for the hint mode could be changed, or at least removed. Currently it's always black with some transparency (so some shade of gray). As of now, only the background color of the hint rectangles and the text color can be changed.

The other modes were able to display graphics without a background, so I don't think there's a technical limitation (I've already spent a few hours messing around the X window functions to no avail, but I barely know C or X11 so it's not surprising)

With the proper hint rectangle background color, the gray background is not really needed anyway, so it's just making the modes more visually consistent.

**Comment by rvaiya** [comment]
There is no shadow :P. I assume you are running a compositor which automatically adds one. After digging through the picom source I found a way to automatically disable this for compton based compositors, which you can find in the latest commit. Let me know if this does the trick. Alternatively you should be able to manually create a rule in your config file.

**Comment by akazukin5151** [comment]
Thank you so much, it worked! I was indeed using picom, wonder how you knew. I didn't think of the compositor at all

**Comment by rvaiya** [comment]
Lucky guess. There seems to be some overlap between the i3/picom and warpd crowds :P.
