### ISSUE TITLE
Doesn't detect keybinds

### ISSUE THREAD

**Issue by glibg10b** [rvaiya/warpd#73]
- No `~/.config/warpd/warpd.log`
- When passing `-f`, just prints `Starting warpd: 1.0.3-beta`
- I'm correctly interpreting e.g. `A-M-c` as Alt + Windows key + C
- KDE Plasma (X)
- No conflicting binds -- when pressing a shortcut, it just gets passed to the focused application (e.g. a terminal prints `^[[99;11u`)
- Warpd is using 0.0% CPU and 7.2 MB of memory

**Comment by aelliott2000** [comment]
I had this same problem. For me the issue was NumLock, which caused Mod2 to be sent with the keys. For example, running `xbindkeys -k` on that combo results in `Alt+Mod2+Mod4 + c`.

Opened up a PR here: https://github.com/rvaiya/warpd/pull/74

**Comment by rvaiya** [comment]
Oops. 0464251e addressed this, but it looks like I forgot to account for this during the rewrite :P.  Thanks for the patch, it has been merged.

@glibg10b 

Does this fix your problem? I haven't had time to try and replicate this yet.

**Comment by glibg10b** [comment]
@rvaiya It works! Well done :D
