### ISSUE TITLE
Starting warpd: 1.0.3-beta ERROR: Failed to grab l (ensure another application hasn't mapped it)

### ISSUE THREAD

**Issue by HappyCthulhu** [rvaiya/warpd#75]
When i trying to start warpd from shell, it returns me:
```
> warpd
daemonizing, log output stored in /home/valera/.config/warpd/warpd.log.
```

This is content of .config/warpd/warpd.log:
```
Starting warpd: 1.0.3-beta
ERROR: Failed to grab l (ensure another application hasn't mapped it)
```

So, what does it mean? Is 'l' == mod or something else? How can i fix that?

P.S. Also, my friend faced same issue (he also i3-user, but on Debian)

Enviropment:
- Ubuntu 20.04 focal KDE neon User Edition 5.22
- i3wm

**Comment by rvaiya** [comment]
It probably means `A-M-l` (the default oneshot hint binding) has already been bound by another program. This seems to be a common problem, so I'm assuming it is probably a stock i3 binding. You can solve it by rebinding A-M-l in the other program or changing `hint_oneshot_key` in your warpd config. I should probably improve the error message to make this less confusing :P.

**Comment by HappyCthulhu** [comment]
cool, thats worked. Also, tell me pls, how to map Caps Lock how exit in config?

I tried:
exit: Caps_Lock
That didnt work for me

**Comment by modernpacifist** [comment]
@HappyCthulhu it should be:
exit: capslock

This issue can be closed, thank you @rvaiya for fast response

**Comment by HappyCthulhu** [comment]
cool, i close this tread

**Comment by Hi-Angel** [comment]
To future readers: the way to work around it through `warpd` means *(as opposed to just unbinding the keys in the system)* is to create a `~/.config/warpd/config` file similar to:

```haskell
hint_oneshot_key: A-M-1
screen_activation_key: A-M-2
```
