### ISSUE TITLE
Can't switch from grid to normal modes

### ISSUE THREAD

**Issue by benvallack** [rvaiya/warpd#81]
Pressing c when in grid mode doesn't seem to switch to normal mode, should it?

Thanks!

**Comment by benvallack** [comment]
Actually not sure this is needed is it as you can just move the grid itself.

**Comment by rvaiya** [comment]
No, the user is expected to exit the mode using `esc` or one of the mouse keys. I will probably implement what you describe in the next release.

**Comment by benvallack** [comment]
Got it, yeah I think it would be useful to be able to switch around between the modes with x c and g as needed once one of them is running.

**Comment by rvaiya** [comment]
This should be implemented in the latest commit.
