### ISSUE TITLE
Confirmation that warpd can work with multiple monitors by treating it as one giant screen

### ISSUE THREAD

**Issue by flubberding** [rvaiya/warpd#83]
Not really an issue. I just wanted to make you aware that warpd indeed treats multiple monitors as one giant screen, as mentioned in the README:

> No multi monitor support (it may still work by treating the entire display as one giant screen, I haven't tried this). If you use this program and desire this feature feel free to harass me via email or file an issue.

I've been using it for the last couple of days one a laptop connected to an external monitor without issues. Both screens are 1080p displays. They are configured as monitors that are next to each other. I'm not sure how well it works when using different resolutions and/or setups that mix landscape and portrait mode.

**Comment by rvaiya** [comment]
Thanks for the additional data point. Unfortunately this is broken on OSX and has a few other shortcomings. I plan on adding proper support for multiscreen setups to the next release. See also #62 .

**Comment by flubberding** [comment]
Thanks for the response! I see I forgot to mention my OS, but I think you figured it out already. But just in case: It's running Manjaro, using the "testing" branch of it's repositories (which are pretty much in sync with the Arch repo's).

**Comment by rvaiya** [comment]
Thanks for letting me know. I've implemented multi-monitor support for both platforms in the latest version.
