### ISSUE TITLE
Custom hint_chars prevents launch

### ISSUE THREAD

**Issue by benvallack** [rvaiya/warpd#88]
When I add this line to my config, warpd doesn't run. 

`hint_chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ`

Is there a limit to the number or an issue with caps?

Thanks!

**Comment by rvaiya** [comment]
Both :P. Capital letters are currently unsupported (they will render but you won't be able to select them), but you are probably running into the hint limit. It shouldn't be too hard to add support for caps, but generally the alphanumeric keys + punctuation should be sufficient, and have the advantage of not requiring the use of the shift key. 

It is worth keeping in mind that the total number of hints is the square of the hint set, so if the above string worked as expected it would yield `52*52 = 2704` hints, which would more than saturate your screen at any reasonable size. If you feel the current number of hints is too small, punctuation should give you a healthy boost without requiring the use of shift (though in your case I understand you will need some chording anyway ;)).

E.G

`abdefghijklmnopqrstuvwxyz;,/[]'`

**Comment by benvallack** [comment]
Ok that makes sense thanks, I have sufficient density/visibility balance now with  

`abcdefghijklmnopqrstuvwxyz.,'[]<>()`

Funnily enough my current 18 key layout has no penalty for caps compared to all the keys on my second alpha layer, and they are all rollable/one shot so no chording for caps. I actually need to chord for the punctuation but not for caps so I would love to see caps supported if possible!

**Comment by benvallack** [comment]
hang on, <>() don't seem to be working

**Comment by rvaiya** [comment]
`<>()` all require shift. Think of them like the capital letters of punctuation :P. Since you've probably forgotten what a normally keyboard looks like, you can use `\[];'./,`  which are all unshifted, as well as any of the number keys. Having said that, I intend to release a patch which should address this shortly.

**Comment by benvallack** [comment]
ah ha yes I had totally forgotten about shift for punctuation!

**Comment by rvaiya** [comment]
This should work in the latest version

**Comment by rvaiya** [comment]
I'm closing this for now. Feel free to reopen it if you encounter any issues.

**Comment by pujvz** [comment]
I would like to be able to use `()[]` in my `hint_chars`. Right now they render but are not selectable. Please let me know if I should open a separate issue.
