### ISSUE TITLE
Red cursor and can't click after update

### ISSUE THREAD

**Issue by benvallack** [rvaiya/warpd#92]
I just updated to the current version and am pleased to see support for caps in the hind mode, however I can no longer click and the cursor has changed from green to red. Has something changed in the config that I need  to update?

**Comment by rvaiya** [comment]
The default cursor colour has changed, though you should be able to click. What does your config look like?

**Comment by benvallack** [comment]
`hint_activation_key: A-C-S-h
hint_chars: abcdefghijklmnopqrstuvwxyz.,'[]
left: n
down: e
up: u
right: a
scroll_down: h
scroll_up: o
oneshot_buttons: t, y, x
buttons: d, comma, .
grid_keys: l,g,s,r
grid_up: u
grid_left: n
grid_down: e
grid_right: a
hint_size: 16
`

**Comment by benvallack** [comment]
Not sure why github isn't preserving the line breaks sorry!

**Comment by rvaiya** [comment]
No worries, the trick is to use triple quote E.G

```
\`\`\`
my
text
\`\`\`
```

> buttons: d, comma, . 

The button delimiter was changed from comma to space in `1.1.1-beta` so you want `buttons: d , .`. You can more easily diagnose issues by using the `-f` flag so errors are printed to stdout.

**Comment by benvallack** [comment]
Perfect, working now many thanks! Good to know for the `-f` flag too cheers!
