### ISSUE TITLE
Allow grid mode to go back to a previous, larger quadrant.

### ISSUE THREAD

**Issue by Xithrius** [rvaiya/warpd#93]
Currently when in grid mode, once you're in a quadrant, you're unable to go back to previous quadrant that you had descended from to be able to navigate to a different area of the screen.

I propose using `Shift + u/i/j/k` to be able to increase quadrant size.

**Comment by rvaiya** [comment]
I have been considering adding an undo button, but it is worth noting that you can already reset the grid using the grid activation key (`g`). A common usage paradigm is to keep your fingers on the grid adjustment keys (`wasd`) to account for any overshoot while you are warping  using the grid keys.

Having said that,  I would generally recommend against using grid mode unless you have a particular reason to favour it over hint mode. Hint mode is much more efficient once you have tuned the number of hints and learned to make minor adjustments using `hjkl`. I almost never find myself using grid mode.

**Comment by Xithrius** [comment]
I don't find myself using it that much either. Thanks for the quick reply, and the extensive config options in the man page!
