### ISSUE TITLE
how to exit the warpd properly?

### ISSUE THREAD

**Issue by BackMountainDevil** [rvaiya/warpd#98]
# info
- os:Linux xx 5.15.32-1-MANJARO #1 SMP PREEMPT Mon Mar 28 09:16:36 UTC 2022 x86_64 GNU/Linux
- warpd: r73.f7d1202

# question

I can start it from terminal with `warpd`. I have seen the readme and man.md. Not really clear how to exit it. Last I just kill it with KDE system monitor. Is that ok?

Is there a way like a icon in system tray to control the warpd start, stop or exit? Just like Screenkey.

**Comment by rvaiya** [comment]
If by 'exit' you mean 'deactivate', you just press the escape key. If you actually want to kill the daemon, then something like `pkill warpd` is indeed what you want. Though the user is expected it running the background.

**Comment by BackMountainDevil** [comment]
Thanks for your reply. I know what you means. I can do deactivate and pkill. Thanks all the same.

From An idea
