### ISSUE TITLE
feature request: configurable exit key for hint mode

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#99]
Hello,

I would like to map exit to `q`, but this would prevent `q` to be used as a selection key in hint mode. Therefore, it would be nice to have a configurable `hint_mode_exit` key, mapped to the same key as `exit` by default.

**Comment by rvaiya** [comment]
Done

**Comment by herrsimon** [comment]
Wow, that was the fastest reply that includes an implementation I ever received. Thanks a lot and have a nice weekend!

**Comment by rvaiya** [comment]
I happened to be in the middle of making some other changes, and it was a fairly small amendment. I will be taking a bit of a hiatus, so don't get used to it ;).
